# Generated by Django 4.2.30 on 2026-08-19 14:00

import apps.analytics.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_project_applicable_regulations_project_approval_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentPerformanceMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255, unique=True)),
                ('turnaround_days', models.DecimalField(decimal_places=1, default=10.0, max_digits=5)),
                ('target_days', models.DecimalField(decimal_places=1, default=14.0, max_digits=5)),
                ('efficiency_percentage', models.IntegerField(default=90)),
                ('workload_level', models.CharField(default='High', max_length=50)),
                ('pending_reviews_count', models.IntegerField(default=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['department_name'],
            },
        ),
        migrations.CreateModel(
            name='OfficerPerformanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('officer_name', models.CharField(max_length=255)),
                ('role', models.CharField(default='Senior Inspector', max_length=255)),
                ('inspections_completed', models.IntegerField(default=45)),
                ('sla_adherence_rate', models.IntegerField(default=95)),
                ('average_review_days', models.DecimalField(decimal_places=1, default=3.2, max_digits=4)),
                ('rank', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessmentAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('structure_name', models.CharField(max_length=255)),
                ('risk_score', models.IntegerField(default=75)),
                ('risk_level', models.CharField(choices=[('Critical', 'Critical Risk'), ('High', 'High Risk'), ('Medium', 'Medium Risk'), ('Low', 'Low Risk')], default='High', max_length=50)),
                ('primary_vulnerability', models.CharField(default='Foundation Settlement Anomaly', max_length=255)),
                ('status', models.CharField(default='Active Alert', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to='projects.project')),
            ],
            options={
                'ordering': ['-risk_score'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_reference', models.CharField(blank=True, db_index=True, default=apps.analytics.models.generate_report_ref, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('Executive', 'Executive Summary Report'), ('Project', 'Project Performance & EVM Report'), ('Inspection', 'Inspection Analytics Report'), ('Compliance', 'Compliance & Regulatory Report'), ('Financial', 'Financial & Revenue Report'), ('Performance', 'Agency SLAs & Performance Report'), ('Custom', 'Custom Multi-Module Report')], default='Custom', max_length=50)),
                ('format', models.CharField(choices=[('PDF', 'PDF Document'), ('CSV', 'CSV Data Sheet'), ('JSON', 'JSON Data Payload')], default='PDF', max_length=20)),
                ('modules_included', models.JSONField(blank=True, default=list)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending Queue'), ('Generating', 'Generating Data'), ('Ready', 'Ready For Download'), ('Failed', 'Generation Failed')], default='Ready', max_length=50)),
                ('file_url', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.CharField(default='1.4 MB', max_length=50)),
                ('generated_by_name', models.CharField(default='Director General', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
