# Generated by Django 4.2.30 on 2026-08-19 10:40

import apps.inspections.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_applicable_regulations_project_approval_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permits', '0002_alter_permit_options_permit_last_renewal_date_and_more'),
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finding',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='inspection',
            options={'ordering': ['-scheduled_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='checklist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checklist',
            name='inspection_type',
            field=models.CharField(default='General Inspection', max_length=100),
        ),
        migrations.AddField(
            model_name='finding',
            name='category',
            field=models.CharField(choices=[('STRUCTURAL', 'Structural Integrity'), ('SAFETY', 'Site Safety & Scaffolding'), ('ENVIRONMENTAL', 'Environmental & Drainage'), ('MEP', 'Mechanical / Electrical / Plumbing'), ('PERMIT_DEVIATION', 'Permit & Drawing Deviation'), ('QUALITY', 'Material Quality & Workmanship')], default='STRUCTURAL', max_length=50),
        ),
        migrations.AddField(
            model_name='finding',
            name='corrective_action_required',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='finding_reference',
            field=models.CharField(blank=True, db_index=True, default=apps.inspections.models.generate_finding_ref, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='finding',
            name='photos',
            field=models.JSONField(blank=True, default=list, help_text='Photo and evidence URLs'),
        ),
        migrations.AddField(
            model_name='finding',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='projects.project'),
        ),
        migrations.AddField(
            model_name='finding',
            name='resolution_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='title',
            field=models.CharField(default='Site Finding', max_length=255),
        ),
        migrations.AddField(
            model_name='finding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='checkin_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='checklist_results',
            field=models.JSONField(blank=True, default=list, help_text='Item by item checklist results'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='gps_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='gps_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='gps_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_reference',
            field=models.CharField(blank=True, db_index=True, default=apps.inspections.models.generate_inspection_ref, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspector_name',
            field=models.CharField(blank=True, default='Unassigned', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='outcome',
            field=models.CharField(choices=[('PENDING', 'Pending Assessment'), ('PASSED', 'Passed'), ('CONDITIONAL_PASS', 'Conditional Pass'), ('FAILED', 'Failed / Violations Found')], default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='inspection',
            name='parent_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='re_inspections', to='inspections.inspection'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='permit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='permits.permit'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='photos_and_evidence',
            field=models.JSONField(blank=True, default=list, help_text='Uploaded photos and evidence urls'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Normal', max_length=50),
        ),
        migrations.AddField(
            model_name='inspection',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inspection',
            name='requested_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='summary_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='items',
            field=models.JSONField(default=list, help_text='List of standard verification items'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_type',
            field=models.CharField(choices=[('Foundation Inspection', 'Foundation Inspection'), ('Structural Review', 'Structural Review'), ('Site Verification', 'Site Verification'), ('Safety Audit', 'Safety Audit'), ('MEP Inspection', 'MEP Inspection'), ('Drainage & Environmental', 'Drainage & Environmental'), ('Final Clearance', 'Final Clearance'), ('Re-Inspection', 'Re-Inspection'), ('Emergency Inspection', 'Emergency Inspection')], default='Foundation Inspection', max_length=100),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('RE_INSPECTION_REQUIRED', 'Re-Inspection Required'), ('FAILED', 'Failed / Stop-Work Issued'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=50),
        ),
        migrations.CreateModel(
            name='StopWorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, db_index=True, default=apps.inspections.models.generate_swo_number, max_length=100, null=True)),
                ('reason', models.TextField()),
                ('severity', models.CharField(default='CRITICAL', max_length=50)),
                ('issued_by_name', models.CharField(default='Building Control Directorate', max_length=255)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / Enforced'), ('APPEALED', 'Pending Appeal'), ('LIFTED', 'Lifted / Reinstated'), ('ENFORCED', 'Tribunal Escalation')], default='ACTIVE', max_length=50)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('lifted_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('lift_justification', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stop_work_orders', to='inspections.finding')),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stop_work_orders', to='inspections.inspection')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_work_orders', to='projects.project')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
