# Generated by Django 4.2.30 on 2026-08-19 19:38

import apps.stakeholders.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stakeholders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=100)),
                ('entity_name', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('incident_count', models.IntegerField(default=1)),
                ('status', models.CharField(default='Blacklisted', max_length=50)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicensedProfessional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_id', models.CharField(db_index=True, default=apps.stakeholders.models.generate_lic_id, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('role_title', models.CharField(max_length=100)),
                ('firm_name', models.CharField(max_length=255)),
                ('license_authority', models.CharField(default='COREN', max_length=100)),
                ('license_status', models.CharField(default='Valid', max_length=50)),
                ('expiry_date', models.CharField(default='Dec 31, 2027', max_length=100)),
                ('active_projects_count', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStakeholderTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_reference', models.CharField(db_index=True, default='PRJ-992', max_length=100)),
                ('project_name', models.CharField(default='Nexus Tower (Phase 1)', max_length=255)),
                ('location', models.CharField(default='Downtown Core', max_length=255)),
                ('status', models.CharField(default='Active Construction', max_length=100)),
                ('team_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='class_category',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='field_expertise',
        ),
        migrations.AddField(
            model_name='consultant',
            name='active_roles_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consultant',
            name='color_theme',
            field=models.CharField(default='bg-emerald-600 text-white', max_length=100),
        ),
        migrations.AddField(
            model_name='consultant',
            name='consultant_id',
            field=models.CharField(db_index=True, default=apps.stakeholders.models.generate_cns_id, max_length=100),
        ),
        migrations.AddField(
            model_name='consultant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='hq_location',
            field=models.CharField(default='Seattle, WA', max_length=255),
        ),
        migrations.AddField(
            model_name='consultant',
            name='name',
            field=models.CharField(default='EcoBalance Partners', max_length=255),
        ),
        migrations.AddField(
            model_name='consultant',
            name='status',
            field=models.CharField(default='Verified', max_length=50),
        ),
        migrations.AddField(
            model_name='contractor',
            name='active_permits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractor',
            name='color_theme',
            field=models.CharField(default='bg-blue-600', max_length=50),
        ),
        migrations.AddField(
            model_name='contractor',
            name='compliance_score',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='contractor',
            name='contractor_id',
            field=models.CharField(db_index=True, default=apps.stakeholders.models.generate_con_id, max_length=100),
        ),
        migrations.AddField(
            model_name='contractor',
            name='contractor_type',
            field=models.CharField(default='General Contractor', max_length=100),
        ),
        migrations.AddField(
            model_name='contractor',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='license_status',
            field=models.CharField(default='Valid', max_length=50),
        ),
        migrations.AddField(
            model_name='contractor',
            name='name',
            field=models.CharField(default='Apex Construction Services', max_length=255),
        ),
        migrations.AddField(
            model_name='contractor',
            name='specialties',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='contractor',
            name='status',
            field=models.CharField(default='Prequalified', max_length=50),
        ),
        migrations.AddField(
            model_name='inspector',
            name='active_inspections',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inspector',
            name='assigned_zone',
            field=models.CharField(default='Zone A (Downtown)', max_length=100),
        ),
        migrations.AddField(
            model_name='inspector',
            name='inspector_id',
            field=models.CharField(db_index=True, default=apps.stakeholders.models.generate_ins_id, max_length=100),
        ),
        migrations.AddField(
            model_name='inspector',
            name='inspector_type',
            field=models.CharField(default='Internal (Gov)', max_length=100),
        ),
        migrations.AddField(
            model_name='inspector',
            name='name',
            field=models.CharField(default='Marcus Chen', max_length=255),
        ),
        migrations.AddField(
            model_name='inspector',
            name='ncrs_issued',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inspector',
            name='pass_rate',
            field=models.CharField(default='88%', max_length=50),
        ),
        migrations.AddField(
            model_name='inspector',
            name='role_title',
            field=models.CharField(default='Structural Inspector', max_length=100),
        ),
        migrations.AlterField(
            model_name='certification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='specialty',
            field=models.CharField(default='Environmental', max_length=100),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StakeholderMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_name', models.CharField(default='Agency Officer', max_length=255)),
                ('sender_role', models.CharField(default='Government Safety Directorate', max_length=100)),
                ('channel_name', models.CharField(db_index=True, default='General Council', max_length=100)),
                ('project_name', models.CharField(default='Central Metro Transit Hub', max_length=255)),
                ('message_text', models.TextField()),
                ('attachment_url', models.CharField(blank=True, max_length=500, null=True)),
                ('attachment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StakeholderMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting_reference', models.CharField(db_index=True, default=apps.stakeholders.models.generate_mtg_id, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('agenda', models.TextField()),
                ('project_name', models.CharField(default='Central Metro Transit Hub', max_length=255)),
                ('date', models.CharField(default='Oct 24, 2026', max_length=100)),
                ('time_slot', models.CharField(default='10:00 AM - 11:30 AM', max_length=100)),
                ('meeting_type', models.CharField(choices=[('Video Call', 'Live Video Conference'), ('Audio Call', 'Audio Conference Call'), ('In-Person Council', 'In-Person Council Session')], default='Video Call', max_length=50)),
                ('initiator_name', models.CharField(default='Engr. Babatunde Sanwo', max_length=255)),
                ('initiator_role', models.CharField(default='Agency Head / Director General', max_length=100)),
                ('room_id', models.CharField(default=apps.stakeholders.models.generate_room_id, max_length=100)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress / Call Live'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=50)),
                ('participants', models.JSONField(default=list)),
                ('minutes_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('developer_id', models.CharField(db_index=True, default=apps.stakeholders.models.generate_dev_id, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(default='Verified', max_length=50)),
                ('active_projects_count', models.IntegerField(default=0)),
                ('portfolio_value', models.CharField(default='$1.2B', max_length=100)),
                ('hq_location', models.CharField(default='New York, NY', max_length=255)),
                ('primary_contact_name', models.CharField(default='Michael Thorne', max_length=255)),
                ('primary_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('primary_contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('color_theme', models.CharField(default='bg-blue-600', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
