# Generated by Django 4.2.30 on 2026-08-25 20:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0002_blacklistrecord_licensedprofessional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingActionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('assignee_name', models.CharField(default='Project Lead', max_length=255)),
                ('due_date', models.CharField(default='Within 5 Business Days', max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='stakeholders.stakeholdermeeting')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_language', models.CharField(db_index=True, max_length=10)),
                ('translated_content', models.TextField()),
                ('provider', models.CharField(default='Google Cloud Translation', max_length=100)),
                ('translation_version', models.CharField(default='v3.0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='stakeholders.stakeholdermessage')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('message', 'target_language')},
            },
        ),
    ]
