# Generated by Django 4.2.30 on 2026-08-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0003_meetingactionitem_messagetranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholdermeeting',
            name='google_meet_url',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
