# Generated by Django 4.2.30 on 2026-08-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0004_stakeholdermeeting_google_meet_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholdermessage',
            name='attachment_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stakeholdermessage',
            name='attachment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stakeholdermessage',
            name='voice_note_duration',
            field=models.IntegerField(default=0, help_text='Duration in seconds'),
        ),
        migrations.AddField(
            model_name='stakeholdermessage',
            name='voice_note_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stakeholdermessage',
            name='attachment_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stakeholdermessage',
            name='message_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
