# Generated by Django 4.2.30 on 2026-08-12 18:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('lga', models.CharField(help_text='Local Government Area', max_length=100)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active Construction'), ('SUSPENDED', 'Suspended / Stop-Work'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='PLANNING', max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='GNSS Point location', null=True, srid=4326)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Site boundaries', null=True, srid=4326)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('estimated_completion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('target_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
        ),
    ]
