services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://api.nexucon.net}
        NEXT_PUBLIC_FRONTEND_URL: ${NEXT_PUBLIC_FRONTEND_URL:-https://nexucon.net}
        NEXT_PUBLIC_APP_NAME: ${NEXT_PUBLIC_APP_NAME:-Nexucon}
        NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME:-}
        NEXT_PUBLIC_CLOUDINARY_API_KEY: ${NEXT_PUBLIC_CLOUDINARY_API_KEY:-}
        NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET: ${NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET:-}
        NEXT_PUBLIC_CLOUDFLARE_R2_BUCKET_NAME: ${NEXT_PUBLIC_CLOUDFLARE_R2_BUCKET_NAME:-}
        NEXT_PUBLIC_CLOUDFLARE_R2_API_URL: ${NEXT_PUBLIC_CLOUDFLARE_R2_API_URL:-}
        NEXT_PUBLIC_CLOUDFLARE_R2_ENDPOINT: ${NEXT_PUBLIC_CLOUDFLARE_R2_ENDPOINT:-}
    container_name: nexucon-frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
