# Generated by Django 4.2.30 on 2026-08-19 14:42

import apps.notifications.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_critical_alerts', models.BooleanField(default=True)),
                ('email_daily_digest', models.BooleanField(default=True)),
                ('email_approval_requests', models.BooleanField(default=True)),
                ('email_inspection_updates', models.BooleanField(default=True)),
                ('email_compliance_ncrs', models.BooleanField(default=True)),
                ('sms_emergency_alerts', models.BooleanField(default=True)),
                ('in_app_sound', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_reference', models.CharField(blank=True, db_index=True, default=apps.notifications.models.generate_notif_ref, max_length=100, null=True)),
                ('recipient_role', models.CharField(default='All', max_length=100)),
                ('category', models.CharField(choices=[('CRITICAL', 'Critical Incident / Blocker'), ('APPLICATIONS', 'New Applications & Permits'), ('INSPECTIONS', 'Inspection Requests & Walkthroughs'), ('COMPLIANCE', 'Compliance & Infraction Alerts'), ('APPROVALS', 'Approval Queue & Sign-offs'), ('OVERDUE', 'Overdue SLA Actions'), ('GENERAL', 'General System Notification')], default='GENERAL', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('snippet', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Critical', 'Critical Priority'), ('High', 'High Priority'), ('Medium', 'Medium Priority'), ('Low', 'Low Priority')], default='Medium', max_length=50)),
                ('severity', models.CharField(default='Normal', max_length=50)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('action_url', models.CharField(blank=True, max_length=255, null=True)),
                ('action_required', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
