# Generated by Django 4.2.30 on 2026-08-19 12:07

import apps.bim.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_project_applicable_regulations_project_approval_date_and_more'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BIMModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_reference', models.CharField(blank=True, db_index=True, default=apps.bim.models.generate_mdl_ref, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('discipline', models.CharField(choices=[('Architecture', 'Architecture'), ('MEP', 'Mechanical / Electrical / Plumbing (MEP)'), ('Structural', 'Structural Engineering'), ('Multi-Disciplinary', 'Multi-Disciplinary / Federated'), ('Civil/Infrastructure', 'Civil / Infrastructure'), ('Landscape', 'Landscape & Site Planning')], default='Architecture', max_length=50)),
                ('format', models.CharField(default='IFC4', max_length=50)),
                ('file_url', models.CharField(blank=True, default='https://assets.nexucon.com/bim/sample_model.ifc', max_length=500, null=True)),
                ('file_size', models.CharField(default='345 MB', max_length=50)),
                ('current_version', models.CharField(default='v1.0', max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Under Review', 'Under Review'), ('Approved', 'Approved & Certified'), ('Changes Requested', 'Changes Requested'), ('Archived', 'Archived')], default='Active', max_length=50)),
                ('is_digitally_certified', models.BooleanField(default=False)),
                ('certified_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('certified_at', models.DateTimeField(blank=True, null=True)),
                ('hash_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('lod', models.CharField(default='LOD 300', max_length=50)),
                ('element_count', models.IntegerField(default=12450)),
                ('coordinate_system', models.JSONField(blank=True, default=dict, help_text='Georeferencing CRS and origin coordinates')),
                ('uploaded_by_name', models.CharField(default='BIM Coordinator', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bim_models', to='projects.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_bim_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BIMProgressValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_status', models.CharField(choices=[('ON_TRACK', 'On Track'), ('DELAYED', 'Delayed'), ('AHEAD', 'Ahead of Schedule')], default='ON_TRACK', max_length=50)),
                ('days_variance', models.IntegerField(default=0, help_text='Negative for days behind, positive for days ahead')),
                ('completed_elements_count', models.IntegerField(default=4205)),
                ('total_elements_count', models.IntegerField(default=9500)),
                ('earned_value_usd', models.CharField(default='$2.4M', max_length=50)),
                ('planned_vs_actual', models.JSONField(blank=True, default=list)),
                ('simulation_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_validations', to='bim.bimmodel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bim_progress_validations', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BIMModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_label', models.CharField(default='v1.0', max_length=50)),
                ('commit_hash', models.CharField(default='a8f93bc2', max_length=50)),
                ('changes_summary', models.TextField(blank=True, null=True)),
                ('author_name', models.CharField(default='Lead Architect', max_length=255)),
                ('author_role', models.CharField(default='BIM Coordinator', max_length=255)),
                ('stats_added', models.IntegerField(default=0)),
                ('stats_modified', models.IntegerField(default=0)),
                ('stats_removed', models.IntegerField(default=0)),
                ('file_url', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.CharField(default='345 MB', max_length=50)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='bim.bimmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BIMClash',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clash_reference', models.CharField(blank=True, db_index=True, default=apps.bim.models.generate_cls_ref, max_length=100, null=True)),
                ('clash_type', models.CharField(choices=[('HARD_CLASH', 'Hard Clash / Physical Intersection'), ('SOFT_CLASH', 'Soft Clash / Clearance Violation'), ('CLEARANCE', 'Egress & Accessibility Clearance'), ('DUPLICATE', 'Duplicate Element')], default='HARD_CLASH', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='HIGH', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('IN_REVIEW', 'In Review'), ('RESOLVED', 'Resolved'), ('CONVERTED_TO_ISSUE', 'Converted to Site Issue')], default='OPEN', max_length=50)),
                ('assigned_to_name', models.CharField(default='MEP Engineer', max_length=255)),
                ('assigned_discipline', models.CharField(default='MEP', max_length=100)),
                ('coordinates_3d', models.JSONField(blank=True, default=dict, help_text='3D spatial coordinates {x, y, z}')),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_site_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_bim_clashes', to='monitoring.siteissue')),
                ('primary_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_clashes', to='bim.bimmodel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bim_clashes', to='projects.project')),
                ('secondary_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_clashes', to='bim.bimmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BIMAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annotation_reference', models.CharField(blank=True, db_index=True, default=apps.bim.models.generate_ann_ref, max_length=100, null=True)),
                ('author_name', models.CharField(default='Sarah Jenkins', max_length=255)),
                ('author_role', models.CharField(default='Lead Architect', max_length=255)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=50)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('viewpoint_camera', models.JSONField(blank=True, default=dict)),
                ('element_ids', models.JSONField(blank=True, default=list)),
                ('comments_count', models.IntegerField(default=0)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='bim.bimmodel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bim_annotations', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
