# Generated by Django 4.2.30 on 2026-08-23 20:50

import apps.bim.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_applicable_regulations_project_approval_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoring', '0003_siteverification_cadastral_beacon_numbers_and_more'),
        ('bim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BIMConstructionMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('milestone_code', models.CharField(db_index=True, default=apps.bim.models.generate_bim_ms_code, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('phase', models.CharField(choices=[('SUBSTRUCTURE', 'Substructure & Foundation Piling'), ('STRUCTURAL_FRAME', 'Reinforced Concrete Superstructure Frame'), ('SUPERSTRUCTURE', 'Superstructure & Floor Slabs'), ('MEP_ROUGHIN', 'MEP Services & Conduit Rough-ins'), ('FACADE_ENVELOPE', 'Facade Glazing, Cladding & Building Envelope'), ('FINISHES', 'Internal Partitions, Screed & Architectural Finishes'), ('COMMISSIONING', 'Testing, Statutory Commissioning & Handover')], default='SUPERSTRUCTURE', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('sequence_order', models.IntegerField(default=1)),
                ('target_date', models.DateField(default=django.utils.timezone.now)),
                ('actual_verified_date', models.DateField(blank=True, null=True)),
                ('bim_elements', models.JSONField(blank=True, default=list, help_text='Element GUIDs, categories, element count, and LOD requirement')),
                ('tolerance_max_mm', models.FloatField(default=15.0, help_text='Max allowable BIM spatial tolerance in mm')),
                ('bim_deviation_mm', models.FloatField(default=0.0, help_text='Measured LiDAR/point cloud deviation in mm')),
                ('gnss_survey_variance_mm', models.FloatField(default=0.0, help_text='Measured GNSS RTK survey variance in mm')),
                ('gpr_clearance_status', models.CharField(choices=[('NOT_APPLICABLE', 'Not Applicable'), ('PENDING', 'Pending Subsurface Scan'), ('VERIFIED', 'Clear / Verified'), ('ANOMALY_DETECTED', 'Anomaly / Utility Collision Detected')], default='NOT_APPLICABLE', max_length=50)),
                ('gpr_evidence_notes', models.TextField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified / In Planning'), ('PENDING_REVIEW', 'Pending BIM Verification Review'), ('VERIFIED', 'Verified & Digitally Stamped'), ('DEVIATION_FLAGGED', 'Deviation Flagged / Non-Compliant'), ('RE_VERIFICATION_REQUIRED', 'Re-Verification Required (Model Revision)'), ('COMPLETED', 'Milestone Completed & Certified')], default='UNVERIFIED', max_length=50)),
                ('digital_stamp_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('verified_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('linked_clashes', models.JSONField(blank=True, default=list, help_text='Linked BIM clashes [{id, ref, title, severity, status}]')),
                ('linked_inspections', models.JSONField(blank=True, default=list, help_text='Linked field inspections [{id, ref, type, outcome, status}]')),
                ('linked_site_verifications', models.JSONField(blank=True, default=list, help_text='Linked site verifications [{id, code, type, status, variance_mm}]')),
                ('linked_ncrs', models.JSONField(blank=True, default=list, help_text='Linked compliance non-conformance reports [{id, ref, title, severity, status}]')),
                ('evidence_vault', models.JSONField(blank=True, default=list, help_text='3D viewpoint snapshots, point clouds, inspection certificates [{name, url, file_type, category, timestamp}]')),
                ('verification_requirements', models.JSONField(blank=True, default=dict, help_text='Gate rules required to achieve verified status')),
                ('signoff_metadata', models.JSONField(blank=True, default=dict, help_text='Digital signature hash, signing officer, role, cert timestamp')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bim_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='bim.bimmodel')),
                ('linked_construction_milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bim_milestones', to='monitoring.constructionmilestone')),
                ('model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_milestones', to='bim.bimmodelversion')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bim_milestones', to='projects.project')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_bim_milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence_order', 'target_date'],
            },
        ),
    ]
