# Generated by Django 4.2.30 on 2026-08-23 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bim', '0002_bimconstructionmilestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimprogressvalidation',
            name='simulation_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
