# Generated by Django 4.2.30 on 2026-08-19 10:48

import apps.monitoring.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_applicable_regulations_project_approval_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_reference', models.CharField(blank=True, db_index=True, default=apps.monitoring.models.generate_vrf_ref, max_length=100, null=True)),
                ('method', models.CharField(choices=[('GNSS_RTK_SURVEY', 'Tersus Oscar GNSS RTK Rover'), ('TERSU_ROVER', 'Tersus GNSS Rover Calibration'), ('GPR_SCAN', 'Ground Penetrating Radar (GPR) Scan'), ('DRONE_PHOTOGRAMMETRY', 'Aerial Drone Photogrammetry'), ('TOTAL_STATION', 'Total Station Coordinate Survey')], default='GNSS_RTK_SURVEY', max_length=50)),
                ('device_identifier', models.CharField(default='Tersus Oscar GNSS RTK #042', max_length=255)),
                ('boundary_coordinates', models.JSONField(blank=True, default=list, help_text='Approved site perimeter boundary points')),
                ('captured_coordinates', models.JSONField(blank=True, default=dict, help_text='Field measured coordinates {lat, lng, elevation}')),
                ('approved_coordinates', models.JSONField(blank=True, default=dict, help_text='Approved CAD/GIS coordinates {lat, lng, elevation}')),
                ('variance_meters', models.FloatField(default=0.0, help_text='Calculated deviation in meters')),
                ('variance_detected', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('VERIFIED', 'Verified'), ('VARIANCE_DETECTED', 'Variance Detected'), ('FLAGGED', 'Flagged for Review')], default='PENDING_VERIFICATION', max_length=50)),
                ('verified_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_reference', models.CharField(blank=True, db_index=True, default=apps.monitoring.models.generate_iss_ref, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=50)),
                ('assigned_to_name', models.CharField(default='Site Engineer', max_length=255)),
                ('reported_by_name', models.CharField(default='Monitoring Officer', max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('resolution_evidence', models.JSONField(blank=True, default=list)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('is_escalated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_issues', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observation_reference', models.CharField(blank=True, db_index=True, default=apps.monitoring.models.generate_obs_ref, max_length=100, null=True)),
                ('category', models.CharField(choices=[('QUALITY', 'Quality & Workmanship'), ('SAFETY', 'Safety & Scaffolding'), ('PROGRESS', 'Progress & Pacing'), ('ENVIRONMENTAL', 'Environmental & Drainage'), ('GENERAL', 'General Site Condition')], default='QUALITY', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('ACTION_REQUIRED', 'Action Required'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=50)),
                ('assigned_officer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('observed_by_name', models.CharField(default='Government Field Inspector', max_length=255)),
                ('gps_coordinates', models.JSONField(blank=True, default=dict)),
                ('evidence_photos', models.JSONField(blank=True, default=list)),
                ('corrective_action', models.TextField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_observations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_observations', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailySiteUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('update_reference', models.CharField(blank=True, db_index=True, default=apps.monitoring.models.generate_upd_ref, max_length=100, null=True)),
                ('update_type', models.CharField(choices=[('DAILY_PHOTO', 'Daily Photo Update'), ('DRONE_SURVEY', 'Comprehensive Drone Survey'), ('PROGRESS_REPORT', 'Progress Update'), ('SITE_LOG', 'General Site Log')], default='DAILY_PHOTO', max_length=50)),
                ('reported_by_name', models.CharField(default='Site Supervisor', max_length=255)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Estimated progress 0-100%')),
                ('work_summary', models.TextField()),
                ('photos', models.JSONField(blank=True, default=list, help_text='List of photo URLs and metadata')),
                ('drone_survey_data', models.JSONField(blank=True, default=dict, help_text='Flight stats, point cloud / orthomosaic links')),
                ('weather_condition', models.CharField(default='Clear / Sunny', max_length=100)),
                ('workforce_count', models.IntegerField(default=0)),
                ('gps_coordinates', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending Verification', 'Pending Verification'), ('Approved', 'Approved'), ('Flagged', 'Flagged')], default='Active', max_length=50)),
                ('priority', models.CharField(default='Medium', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_updates', to='projects.project')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_site_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('target_date', models.DateField()),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('DUE_THIS_WEEK', 'Due This Week'), ('VERIFIED', 'Verified'), ('DELAYED', 'Delayed'), ('COMPLETED', 'Completed')], default='UPCOMING', max_length=50)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('verified_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_documents', models.JSONField(blank=True, default=list)),
                ('is_delayed', models.BooleanField(default=False)),
                ('delay_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_milestones', to='projects.project')),
            ],
            options={
                'ordering': ['target_date'],
            },
        ),
    ]
