# Generated by Django 4.2.30 on 2026-08-23 09:09

import apps.monitoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructionmilestone',
            options={'ordering': ['sequence_order', 'target_date']},
        ),
        migrations.AddField(
            model_name='constructionmilestone',
            name='actual_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='constructionmilestone',
            name='baseline_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='constructionmilestone',
            name='baseline_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='constructionmilestone',
            name='bim_deviation_mm',
            field=models.FloatField(default=0.0, help_text='LiDAR/point cloud deviation in mm'),
        ),
        migrations.AddField(
            model_name='constructionmilestone',
            name='bim_tolerance_max_mm',
            field=models.FloatField(default=15.0, help_text='Max allowable BIM tolerance in mm'),
        ),
        migrations.AddField(
            model_name='constructionmilestone',
            name='critical_path',
            field=models.BooleanField(default=False, help_text='Designates if milestone is on the project critical path'),
        ),
        migrations.AddField(
            model_name='constructionmilestone',
            name='dependencies',
            field=models.JSONField(blank=True, default=list, help_text='Predecessor milestone objects [{id, code, name, is_blocking}]'),
        ),
        migrations.AddField(
            model_name='constructionmilestone',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='constructionmilestone',
            name='digital_eye_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='constructionmilestone',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='constructionmilestone',
            name='evidence_photos',
            field=models.JSONField(blank=True, default=list, help_text='Progress site photos [{url, caption, timestamp}]'),
        ),
        migrations.AddField(
            model_name='constructionmilestone',
            name='linked_bim_model_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='constructionmilestone',
            name='linked_inspection_ids',
            field=models.JSONField(blank=True, default=list, help_text='Linked field inspection records [{id, ref, type, status, outcome}]'),
        ),
        migrations.AddField(
            model_name='constructionmilestone',
            name='linked_issue_ids',
            field=models.JSONField(blank=True, default=list, help_text='Linked site issues/defects [{id, ref, title, severity, status}]'),
        ),
        migrations.AddField(
            model_name='constructionmilestone',
            name='milestone_code',
            field=models.CharField(db_index=True, default=apps.monitoring.models.generate_ms_code, max_length=50),
        ),
        migrations.AddField(
            model_name='constructionmilestone',
            name='phase',
            field=models.CharField(choices=[('SUBSTRUCTURE', 'Substructure & Foundation Piling'), ('STRUCTURAL_FRAME', 'Reinforced Concrete Superstructure Frame'), ('SUPERSTRUCTURE', 'Superstructure & Floor Slabs'), ('MEP_ROUGHIN', 'MEP Services & Conduit Rough-ins'), ('FACADE_ENVELOPE', 'Facade Glazing, Cladding & Building Envelope'), ('FINISHES', 'Internal Partitions, Screed & Architectural Finishes'), ('COMMISSIONING', 'Testing, Statutory Commissioning & Handover')], default='SUPERSTRUCTURE', max_length=50),
        ),
        migrations.AddField(
            model_name='constructionmilestone',
            name='physical_progress_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='constructionmilestone',
            name='planned_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='constructionmilestone',
            name='risk_factors',
            field=models.JSONField(blank=True, default=list, help_text='Dynamic risk justification points'),
        ),
        migrations.AddField(
            model_name='constructionmilestone',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low Risk (On Schedule)'), ('MEDIUM', 'Medium Risk (Approaching Gate)'), ('HIGH', 'High Risk (Slippage / Defect Present)'), ('CRITICAL', 'Critical Risk (Stop-Work / Gate Failed)')], default='LOW', max_length=20),
        ),
        migrations.AddField(
            model_name='constructionmilestone',
            name='sequence_order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='constructionmilestone',
            name='survey_variance_meters',
            field=models.FloatField(default=0.0, help_text='GNSS RTK rover coordinate variance in meters'),
        ),
        migrations.AddField(
            model_name='constructionmilestone',
            name='variance_days',
            field=models.IntegerField(default=0, help_text='Calculated schedule variance in days (+ is delayed, - is ahead)'),
        ),
        migrations.AddField(
            model_name='constructionmilestone',
            name='verification_requirements',
            field=models.JSONField(blank=True, default=dict, help_text='Configured gate checks required for signoff'),
        ),
        migrations.AddField(
            model_name='constructionmilestone',
            name='verification_signoff',
            field=models.JSONField(blank=True, default=dict, help_text='Digital signoff, certificate ref, signature hash'),
        ),
        migrations.AlterField(
            model_name='constructionmilestone',
            name='evidence_documents',
            field=models.JSONField(blank=True, default=list, help_text='Uploaded test certs, lab reports, structural signoffs [{name, url, file_type, size, category}]'),
        ),
        migrations.AlterField(
            model_name='constructionmilestone',
            name='progress_percentage',
            field=models.IntegerField(default=0, help_text='Physical progress 0-100%'),
        ),
        migrations.AlterField(
            model_name='constructionmilestone',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('DUE_THIS_WEEK', 'Due This Week'), ('PENDING_VERIFICATION', 'Pending Verification'), ('VERIFIED', 'Verified & Certified'), ('COMPLETED', 'Completed'), ('DELAYED', 'Delayed'), ('BLOCKED', 'Blocked / Non-Compliant'), ('ON_HOLD', 'On Hold'), ('UPCOMING', 'Upcoming')], default='PLANNED', max_length=50),
        ),
        migrations.AlterField(
            model_name='constructionmilestone',
            name='target_date',
            field=models.DateField(help_text='Planned target completion date'),
        ),
    ]
