# Generated by Django 4.2.30 on 2026-08-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_constructionmilestone_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteverification',
            name='cadastral_beacon_numbers',
            field=models.JSONField(blank=True, default=list, help_text="Cadastral beacon pillar IDs e.g. ['BC-LA-2026/089', 'BC-LA-2026/090']"),
        ),
        migrations.AddField(
            model_name='siteverification',
            name='digital_cert_ref',
            field=models.CharField(blank=True, help_text='Statutory certificate reference e.g. CERT-VRF-2026-0042', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteverification',
            name='elevation_variance_meters',
            field=models.FloatField(default=0.0, help_text='Calculated vertical elevation offset in meters'),
        ),
        migrations.AddField(
            model_name='siteverification',
            name='encroachment_details',
            field=models.TextField(blank=True, help_text='Encroachment specifics and affected boundary offsets', null=True),
        ),
        migrations.AddField(
            model_name='siteverification',
            name='encroachment_detected',
            field=models.BooleanField(default=False, help_text='True if structure encroaches beyond approved building boundary line'),
        ),
        migrations.AddField(
            model_name='siteverification',
            name='evidence_documents',
            field=models.JSONField(blank=True, default=list, help_text='Certified survey plans, RINEX raw logs, calibration certs'),
        ),
        migrations.AddField(
            model_name='siteverification',
            name='evidence_photos',
            field=models.JSONField(blank=True, default=list, help_text='Benchmark site photos, beacon tripod setups'),
        ),
        migrations.AddField(
            model_name='siteverification',
            name='signature_hash',
            field=models.CharField(blank=True, help_text='SHA-256 cryptographic verification signature', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteverification',
            name='telemetry_data',
            field=models.JSONField(blank=True, default=dict, help_text='Live RTK rover metrics {satellites, hdop, vdop, rtk_fix, latency_sec}'),
        ),
        migrations.AddField(
            model_name='siteverification',
            name='tolerance_limit_meters',
            field=models.FloatField(default=0.05, help_text='Allowable regulatory threshold in meters (default 50mm)'),
        ),
        migrations.AddField(
            model_name='siteverification',
            name='verified_by_role',
            field=models.CharField(blank=True, default='Directorate of Cadastral & Structural Survey', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='siteverification',
            name='approved_coordinates',
            field=models.JSONField(blank=True, default=dict, help_text='Approved Masterplan/Planning coordinates {lat, lng, elevation}'),
        ),
        migrations.AlterField(
            model_name='siteverification',
            name='boundary_coordinates',
            field=models.JSONField(blank=True, default=list, help_text='Approved site perimeter boundary polygon points'),
        ),
        migrations.AlterField(
            model_name='siteverification',
            name='captured_coordinates',
            field=models.JSONField(blank=True, default=dict, help_text='Field measured coordinates {lat, lng, elevation, accuracy_horizontal_mm}'),
        ),
        migrations.AlterField(
            model_name='siteverification',
            name='method',
            field=models.CharField(choices=[('GNSS_RTK_SURVEY', 'Tersus Oscar GNSS RTK Rover'), ('TERSU_ROVER', 'Tersus GNSS Rover Calibration'), ('DRONE_PHOTOGRAMMETRY', 'Aerial Drone Photogrammetry & LiDAR'), ('GPR_SCAN', 'Ground Penetrating Radar (GPR) Scan'), ('TOTAL_STATION', 'Total Station Cadastral Survey'), ('SETBACK_AUDIT', 'Statutory Building Setback Audit'), ('LEVEL_ELEVATION', 'Foundation Datum Elevation Check')], default='GNSS_RTK_SURVEY', max_length=50),
        ),
        migrations.AlterField(
            model_name='siteverification',
            name='status',
            field=models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('IN_PROGRESS', 'Survey In Progress'), ('VERIFIED', 'Verified & Certified'), ('VARIANCE_DETECTED', 'Variance Detected'), ('FLAGGED', 'Flagged for Review / SWO'), ('RESOLVED', 'Resolved & Remediated')], default='PENDING_VERIFICATION', max_length=50),
        ),
        migrations.AlterField(
            model_name='siteverification',
            name='variance_detected',
            field=models.BooleanField(default=False, help_text='True if variance exceeds tolerance limit'),
        ),
        migrations.AlterField(
            model_name='siteverification',
            name='variance_meters',
            field=models.FloatField(default=0.0, help_text='Calculated horizontal spatial deviation in meters'),
        ),
    ]
