# Generated by Django 4.2.30 on 2026-08-19 15:06

import apps.audit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='audit_reference',
            field=models.CharField(blank=True, db_index=True, default=apps.audit.models.generate_audit_ref, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='project_name',
            field=models.CharField(default='Central Metro Transit Hub', max_length=255),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='severity',
            field=models.CharField(choices=[('Normal', 'Normal Event'), ('Warning', 'Warning / Infraction'), ('High', 'High Priority Action'), ('Critical', 'Critical / Security Event')], default='Normal', max_length=50),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='signature_hash',
            field=models.CharField(default='0x8f4e2c9b1a7d3e5f', max_length=255),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='user_name',
            field=models.CharField(default='System Officer', max_length=255),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='user_role',
            field=models.CharField(default='Government Officer', max_length=100),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='resource_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
