# Generated by Django 4.2.30 on 2026-08-25 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0002_auditevent_audit_reference_auditevent_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='resource_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='severity',
            field=models.CharField(choices=[('Normal', 'Normal Event'), ('Warning', 'Warning / Infraction'), ('High', 'High Priority Action'), ('Critical', 'Critical / Security Event')], db_index=True, default='Normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
