# Generated by Django 4.2.30 on 2026-08-12 18:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporter_name', models.CharField(blank=True, help_text='Can be anonymous', max_length=150, null=True)),
                ('reporter_contact', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('evidence_url', models.URLField(blank=True, help_text='Link to uploaded photo/video', null=True)),
                ('status', models.CharField(choices=[('NEW', 'New / Unverified'), ('INVESTIGATING', 'Under Investigation'), ('VERIFIED', 'Verified / Action Taken'), ('DISMISSED', 'Dismissed / Invalid')], default='NEW', max_length=50)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
