# Generated by Django 4.2.30 on 2026-08-19 13:29

import apps.approvals.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_project_applicable_regulations_project_approval_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_reference', models.CharField(blank=True, db_index=True, default=apps.approvals.models.generate_request_ref, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('request_type', models.CharField(choices=[('Document', 'Document Signature'), ('Technical', 'Technical & Engineering Review'), ('Permit', 'Permit & License Authorization'), ('Escalated', 'Escalated Blocker / High Value (>₦50M)'), ('General', 'General Administrative Request')], default='General', max_length=50)),
                ('discipline', models.CharField(choices=[('MEP', 'Mechanical, Electrical & Plumbing (MEP)'), ('Structural', 'Structural Engineering'), ('Architecture', 'Architectural Design'), ('Legal', 'Legal & Regulatory'), ('Finance', 'Finance & Budget'), ('Safety', 'Safety & HSE'), ('Procurement', 'Procurement & Contracts'), ('General', 'General Project Management')], default='General', max_length=50)),
                ('priority', models.CharField(choices=[('Critical', 'Critical Priority'), ('High', 'High Priority'), ('Medium', 'Medium Priority'), ('Low', 'Low Priority')], default='Medium', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending Decision'), ('Approved', 'Fully Approved / Executed'), ('Rejected', 'Rejected'), ('Conditional', 'Subject To Conditions'), ('In Review', 'In Technical Review'), ('Awaiting Fix', 'Awaiting Fix / Remediation'), ('Escalated', 'Escalated to Director / DG')], default='Pending', max_length=50)),
                ('value_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('doa_level_required', models.CharField(default='Director', max_length=100)),
                ('submitted_by_name', models.CharField(default='Apex Engineering', max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('bottleneck', models.CharField(blank=True, max_length=255, null=True)),
                ('days_overdue', models.IntegerField(default=0)),
                ('signatories_required', models.IntegerField(default=1)),
                ('signatories_completed', models.IntegerField(default=0)),
                ('attached_file_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='projects.project')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalReviewCriteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pass', 'Passed'), ('fail', 'Failed'), ('pending', 'Pending Evaluation')], default='pending', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='approvals.approvalrequest')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision_reference', models.CharField(blank=True, db_index=True, default=apps.approvals.models.generate_decision_ref, max_length=100, null=True)),
                ('decider_name', models.CharField(default='Director', max_length=255)),
                ('decider_role', models.CharField(default='Director', max_length=255)),
                ('outcome', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected / Denied'), ('Conditional', 'Conditional Approval'), ('Returned For Info', 'Returned For Information'), ('Escalated', 'Escalated to Executive Authority')], max_length=50)),
                ('decision_notes', models.TextField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True, null=True)),
                ('digital_pin_verified', models.BooleanField(default=False)),
                ('signature_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='approvals.approvalrequest')),
                ('decider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
