# Generated by Django 4.2.30 on 2026-08-25 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='assigned_to_name',
            field=models.CharField(blank=True, default='Lead Government Reviewer', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='compliance_gate_status',
            field=models.CharField(default='Passed', max_length=50),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='conditions_met',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='source_entity_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='source_entity_type',
            field=models.CharField(choices=[('PermitApplication', 'Permit Application'), ('Document', 'Project Document / Version'), ('BIMModel', 'BIM Coordination Model'), ('Inspection', 'Site Inspection Report'), ('Milestone', 'Construction Milestone'), ('ComplianceReview', 'Compliance Review / Audit'), ('GPRFinding', 'GPR Subsurface Finding'), ('General', 'General Entity')], default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='source_version_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ApprovalComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(default='Reviewing Official', max_length=255)),
                ('comment_type', models.CharField(choices=[('General', 'General Review Comment'), ('RevisionRequest', 'Formal Revision Request'), ('ConditionVerification', 'Condition Verification'), ('TechnicalFinding', 'Technical / Site Finding')], default='General', max_length=50)),
                ('content', models.TextField()),
                ('attachment_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='approvals.approvalrequest')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
