# Generated by Django 4.2.30 on 2026-08-12 18:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('COLLAPSE', 'Building Collapse'), ('FIRE', 'Fire Incident'), ('STRUCTURAL_FAILURE', 'Critical Structural Failure'), ('OTHER', 'Other Emergency')], max_length=50)),
                ('description', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergencies', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ResponderDispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(help_text='e.g., Fire Service, Police, Paramedics', max_length=100)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('payload_sent', models.JSONField(help_text='GIS location + project details sent')),
                ('status', models.CharField(default='SENT', max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='emergency.emergencyevent')),
            ],
        ),
    ]
