# Generated by Django 4.2.30 on 2026-08-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='application',
            name='assigned_reviewer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='attached_documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='created_by_name',
            field=models.CharField(blank=True, help_text='Inspector/Director who routed this', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='priority',
            field=models.CharField(default='Normal', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='required_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='review_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='review_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
