# Generated by Django 4.2.30 on 2026-08-19 09:40

import apps.applications.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0003_application_application_reference_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='application',
            name='assigned_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='conditions',
            field=models.TextField(blank=True, help_text='Requirements for Conditional Approval', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='decision_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='decision_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='document_requests',
            field=models.JSONField(blank=True, default=list, help_text='List of formal document requests sent to applicant'),
        ),
        migrations.AddField(
            model_name='application',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='application',
            name='fee_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('WAIVED', 'Waived'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='jurisdiction',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_reference',
            field=models.CharField(default=apps.applications.models.generate_application_ref, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_type',
            field=models.CharField(default='Building Permit', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='attached_documents',
            field=models.JSONField(blank=True, default=list, help_text='Uploaded architectural, structural, and EIA documents'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_by_name',
            field=models.CharField(blank=True, help_text='Officer/Director who logged this', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='review_items',
            field=models.JSONField(blank=True, default=list, help_text='Review criteria checklist with status and notes'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('REVIEW_COMPLETED', 'Review Completed'), ('APPROVAL_REQUESTED', 'Approval Requested'), ('CONDITIONAL_APPROVAL', 'Conditional Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('RENEWED', 'Renewed')], default='SUBMITTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='submission_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
