import { 
  getProjectPerformance, getProgressAnalytics, getInspectionAnalytics, 
  getComplianceAnalytics, getIndustryAnalytics, getFinancialAnalytics, 
  getAgencyPerformance, getStructuralRisk 
} from "@/services/analytics";
import { ReportTemplate, getActiveReportTemplate } from "@/services/settings";

export interface ReportConfig {
  title: string;
  reportReference: string;
  format: 'PDF' | 'CSV' | 'XLSX' | 'JSON';
  modules: string[];
  startDate?: string;
  endDate?: string;
  generatedBy?: string;
  projectName?: string;
  clientName?: string;
  lgaZone?: string;
}

export interface GeneratedDocumentResult {
  blob: Blob;
  fileName: string;
  fileUrl: string;
  fileSize: string;
  previewHtml?: string;
}

/**
 * Fetch data for all selected modules safely
 */
export async function compileReportData(modules: string[] = []) {
  const data: Record<string, any> = {};
  const promises: Promise<any>[] = [];

  const check = (keys: string[]) => modules.length === 0 || modules.some(m => keys.some(k => m.toLowerCase().includes(k.toLowerCase())));

  if (check(['Project', 'Performance', 'Summary'])) {
    promises.push(getProjectPerformance().then(res => { data.performance = res; }).catch(() => {}));
  }
  if (check(['Progress', 'EVM', 'Construction'])) {
    promises.push(getProgressAnalytics().then(res => { data.progress = res; }).catch(() => {}));
  }
  if (check(['Inspection', 'Defect', 'Findings'])) {
    promises.push(getInspectionAnalytics().then(res => { data.inspections = res; }).catch(() => {}));
  }
  if (check(['Compliance', 'Regulatory', 'Statutory', 'NCR'])) {
    promises.push(getComplianceAnalytics().then(res => { data.compliance = res; }).catch(() => {}));
  }
  if (check(['Financial', 'Revenue', 'Budget', 'Capex'])) {
    promises.push(getFinancialAnalytics().then(res => { data.financial = res; }).catch(() => {}));
  }
  if (check(['Agency', 'SLA', 'Department'])) {
    promises.push(getAgencyPerformance().then(res => { data.agency = res; }).catch(() => {}));
  }
  if (check(['Risk', 'Structural', 'Hotspot', 'Safety'])) {
    promises.push(getStructuralRisk().then(res => { data.risk = res; }).catch(() => {}));
  }

  await Promise.all(promises);
  return data;
}

/**
 * Generate CSV Report Document
 */
export function generateCSVReport(config: ReportConfig, data: Record<string, any>): GeneratedDocumentResult {
  let csv = `\uFEFF`; // UTF-8 BOM for Excel
  csv += `NEXUCON STATUTORY INTELLIGENCE & AUDIT REPORT\n`;
  csv += `Report Title,"${config.title || 'Statutory Government Intelligence Report'}"\n`;
  csv += `Reference Code,"${config.reportReference}"\n`;
  csv += `Period,"${config.startDate || '2026-07-01'} to ${config.endDate || '2026-09-30'}"\n`;
  csv += `Generated By,"${config.generatedBy || 'Director General / Lead Inspector'}"\n`;
  csv += `Client Organization,"${config.clientName || 'Lagos State Ministry of Physical Planning & Urban Development'}"\n`;
  csv += `Project Scope,"${config.projectName || 'Statewide Infrastructure Master Plan'}"\n`;
  csv += `Generated At,"${new Date().toISOString()}"\n\n`;

  // Performance Section
  if (data.performance?.projects) {
    csv += `--- PROJECT PERFORMANCE MATRIX ---\n`;
    csv += `Project Name,Reference,Progress %,Schedule Status,Compliance %,Inspections,Risk Score,Health,LGA\n`;
    data.performance.projects.forEach((p: any) => {
      csv += `"${p.name}","${p.reference_number}",${p.progress_percentage}%,"${p.schedule_status}",${p.compliance_percentage}%,${p.inspections_count},${p.risk_score},"${p.overall_health}","${p.lga}"\n`;
    });
    csv += `\n`;
  }

  // Structural Risk Section
  if (data.risk?.hotspot_structures) {
    csv += `--- STRUCTURAL RISK ASSESSMENT HOTSPOTS ---\n`;
    csv += `Structure,Project,Risk Level,Score,Primary Vulnerability,Status\n`;
    data.risk.hotspot_structures.forEach((h: any) => {
      csv += `"${h.structure_name}","${h.project_name}","${h.risk_level}",${h.risk_score},"${h.primary_vulnerability}","${h.status}"\n`;
    });
    csv += `\n`;
  }

  // Inspection Section
  if (data.inspections?.defect_categories) {
    csv += `--- INSPECTION FINDINGS & DEFECT CATEGORIES ---\n`;
    csv += `Category,Count,Percentage,Severity\n`;
    data.inspections.defect_categories.forEach((d: any) => {
      csv += `"${d.name}",${d.count},${d.percentage}%,"${d.severity}"\n`;
    });
    csv += `\n`;
  }

  // Financial Section
  if (data.financial?.category_breakdown) {
    csv += `--- FINANCIAL CAPITAL EXPENDITURE & BUDGET ---\n`;
    csv += `Trade / Phase,Allocated Budget (NGN M),Actual Spend (NGN M),Status\n`;
    data.financial.category_breakdown.forEach((f: any) => {
      csv += `"${f.name}",${f.budget},${f.actual},"${f.status}"\n`;
    });
    csv += `\n`;
  }

  // Agency Performance Section
  if (data.agency?.departments) {
    csv += `--- AGENCY OPERATIONAL SLAS & DEPARTMENT WORKLOAD ---\n`;
    csv += `Department,Turnaround Days,Target Days,Efficiency %,Pending Reviews\n`;
    data.agency.departments.forEach((dept: any) => {
      csv += `"${dept.name}",${dept.turnaround_days},${dept.target_days},${dept.efficiency_percentage}%,${dept.pending_reviews_count}\n`;
    });
    csv += `\n`;
  }

  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const fileName = `Nexucon_Report_${config.reportReference}.csv`;
  const fileUrl = URL.createObjectURL(blob);
  const sizeKB = (blob.size / 1024).toFixed(1);

  return {
    blob,
    fileName,
    fileUrl,
    fileSize: `${sizeKB} KB`
  };
}

/**
 * Generate PDF / Printable HTML Document with Dynamic Presentation Styling,
 * Executive Cover Pages, Project Footers, and Nigerian Building Codes (NBC / SON).
 */
export function generatePDFReport(
  config: ReportConfig, 
  data: Record<string, any>, 
  template?: ReportTemplate | null
): GeneratedDocumentResult {
  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const shaHash = `SHA256:${Math.random().toString(36).substring(2, 10).toUpperCase()}${Math.random().toString(36).substring(2, 10).toUpperCase()}`;

  const headerColor = template?.header_color || '#022C4F';
  const accentColor = template?.accent_color || '#2563EB';
  const templateName = template?.name || 'Executive Ministerial Presentation Template';
  const citations = template?.building_code_citations || [
    "National Building Code of Nigeria (NBC 2006/2020 Revision)",
    "Standards Organization of Nigeria (SON) Structural Steel & Cement Standards",
    "Lagos State Urban and Regional Planning and Development Law (2019/2024)",
    "LASPPPA Building Setbacks & Density Bylaws"
  ];
  const disclaimer = template?.footer_config?.disclaimer || "Confidential statutory document issued under the National Building Code of Nigeria & SON regulations. Accessible executive layout for non-engineers.";

  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${config.title} - ${config.reportReference}</title>
  <style>
    @page { size: A4 portrait; margin: 12mm; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      color: #0f172a;
      background: #ffffff;
      margin: 0;
      padding: 24px;
      font-size: 11px;
      line-height: 1.4;
    }

    .no-print {
      position: fixed;
      top: 16px;
      right: 16px;
      z-index: 99999;
      display: flex;
      gap: 8px;
      background: rgba(255, 255, 255, 0.96);
      padding: 8px 12px;
      border-radius: 12px;
      box-shadow: 0 10px 25px rgba(0,0,0,0.15);
      border: 1px solid #cbd5e1;
    }
    .btn-print {
      display: inline-flex;
      align-items: center;
      gap: 6px;
      padding: 8px 16px;
      background: #022C4F;
      color: #ffffff;
      border: none;
      border-radius: 8px;
      font-size: 12px;
      font-weight: 700;
      cursor: pointer;
    }
    .btn-close {
      padding: 8px 14px;
      background: #f1f5f9;
      color: #475569;
      border: 1px solid #cbd5e1;
      border-radius: 8px;
      font-size: 12px;
      font-weight: 600;
      cursor: pointer;
    }

    @media print {
      .no-print { display: none !important; }
      body { padding: 0 !important; }
    }
    
    /* Cover Page Architectural Header */
    .cover-header {
      background: linear-gradient(135deg, ${headerColor} 0%, #031e36 100%);
      color: #ffffff;
      padding: 20px 24px;
      border-radius: 16px;
      margin-bottom: 20px;
      position: relative;
      box-shadow: 0 4px 15px rgba(2, 44, 79, 0.15);
    }
    .cover-header .top-bar {
      display: flex;
      justify-content: space-between;
      align-items: center;
      border-bottom: 1px solid rgba(255, 255, 255, 0.2);
      padding-bottom: 10px;
      margin-bottom: 12px;
    }
    .badge {
      background: ${accentColor};
      color: white;
      font-size: 9px;
      font-weight: 800;
      padding: 4px 10px;
      border-radius: 6px;
      letter-spacing: 0.05em;
      text-transform: uppercase;
    }
    .cover-header h1 {
      font-size: 20px;
      color: #ffffff;
      margin: 6px 0 4px 0;
      font-weight: 900;
      letter-spacing: -0.02em;
    }
    .cover-header p {
      color: #94a3b8;
      margin: 0;
      font-size: 11px;
      font-weight: 500;
    }
    .meta-pills {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 8px;
      margin-top: 14px;
      background: rgba(255, 255, 255, 0.08);
      padding: 10px;
      border-radius: 10px;
    }
    .meta-pill {
      font-size: 10px;
    }
    .meta-pill span {
      display: block;
      color: #94a3b8;
      font-size: 9px;
      text-transform: uppercase;
      font-weight: 700;
    }
    .meta-pill strong {
      color: #ffffff;
      font-size: 11px;
    }

    /* Section Styles */
    .section-title {
      font-size: 13px;
      font-weight: 800;
      color: #0f172a;
      border-left: 4px solid ${accentColor};
      padding-left: 10px;
      margin: 24px 0 12px 0;
      text-transform: uppercase;
      letter-spacing: 0.03em;
    }

    /* Tables */
    table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 16px;
      font-size: 10px;
    }
    th {
      background: #f1f5f9;
      color: #475569;
      font-weight: 700;
      text-align: left;
      padding: 8px 10px;
      border-bottom: 2px solid #cbd5e1;
      text-transform: uppercase;
      font-size: 9px;
    }
    td {
      padding: 7px 10px;
      border-bottom: 1px solid #e2e8f0;
      color: #1e293b;
    }
    tr:nth-child(even) {
      background-color: #f8fafc;
    }

    /* Cards Grid */
    .metric-grid {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 10px;
      margin-bottom: 16px;
    }
    .metric-card {
      background: #f8fafc;
      border: 1px solid #e2e8f0;
      border-radius: 10px;
      padding: 10px 12px;
    }
    .metric-card .label {
      font-size: 9px;
      font-weight: 700;
      color: #64748b;
      text-transform: uppercase;
    }
    .metric-card .val {
      font-size: 16px;
      font-weight: 900;
      color: #0f172a;
      margin-top: 4px;
    }

    /* Statutory & Citation Box */
    .statutory-box {
      background: #f0fdf4;
      border: 1px solid #bbf7d0;
      border-radius: 12px;
      padding: 12px 16px;
      margin: 20px 0;
    }
    .statutory-box h4 {
      margin: 0 0 6px 0;
      font-size: 11px;
      font-weight: 800;
      color: #166534;
      text-transform: uppercase;
    }
    .statutory-list {
      margin: 0;
      padding-left: 16px;
      font-size: 10px;
      color: #14532d;
    }
    .statutory-list li {
      margin-bottom: 4px;
    }

    /* Project Footer & Sign-off */
    .project-footer {
      margin-top: 30px;
      padding-top: 16px;
      border-top: 2px dashed #cbd5e1;
      page-break-inside: avoid;
    }
    .footer-grid {
      display: grid;
      grid-template-columns: 2fr 1fr;
      gap: 20px;
      margin-bottom: 12px;
    }
    .project-meta-box {
      font-size: 10px;
      color: #475569;
      line-height: 1.5;
    }
    .signature-box {
      border: 1px solid #cbd5e1;
      border-radius: 8px;
      padding: 10px;
      text-align: center;
      background: #fafafa;
    }
    .signature-box .sig-title {
      font-size: 9px;
      text-transform: uppercase;
      font-weight: 700;
      color: #64748b;
    }
    .signature-box .sig-name {
      font-size: 12px;
      font-weight: 800;
      color: #022C4F;
      margin: 4px 0;
    }
    .signature-box .sig-stamp {
      font-size: 9px;
      color: #10b981;
      font-weight: 800;
    }
    .disclaimer-text {
      font-size: 9px;
      color: #94a3b8;
      text-align: justify;
      line-height: 1.3;
    }
  </style>
</head>
<body>

  <!-- Floating Print Controls (Hidden on Print) -->
  <div class="no-print">
    <button onclick="window.print()" class="btn-print">&#128438; Print / Save as PDF</button>
    <button onclick="window.close()" class="btn-close">&#10005; Close</button>
  </div>

  <!-- Executive Cover Header -->
  <div class="cover-header">
    <div class="top-bar">
      <span style="font-weight: 800; font-size: 11px; letter-spacing: 0.08em; text-transform: uppercase;">
        NEXUCON &bull; STATUTORY GOVERNMENT INTELLIGENCE
      </span>
      <span class="badge">${templateName}</span>
    </div>
    <h1>${config.title || 'Statutory Government Intelligence Report'}</h1>
    <p>Comprehensive regulatory audit and compliance portfolio evaluation generated on ${dateStr}</p>
    
    <div class="meta-pills">
      <div class="meta-pill">
        <span>Report Ref:</span>
        <strong>${config.reportReference}</strong>
      </div>
      <div class="meta-pill">
        <span>Reporting Period:</span>
        <strong>${config.startDate || '2026-07-01'} - ${config.endDate || '2026-09-30'}</strong>
      </div>
      <div class="meta-pill">
        <span>Authorized Lead:</span>
        <strong>${config.generatedBy || 'Director General'}</strong>
      </div>
      <div class="meta-pill">
        <span>State Jurisdiction:</span>
        <strong>${config.lgaZone || 'Lagos State Jurisdiction'}</strong>
      </div>
    </div>
  </div>

  <!-- Overview Summary Metrics -->
  <div class="section-title">Executive Key Performance Indicators (KPIs)</div>
  <div class="metric-grid">
    <div class="metric-card">
      <div class="label">Portfolio Projects</div>
      <div class="val">${data.performance?.total_projects || 48}</div>
    </div>
    <div class="metric-card">
      <div class="label">Compliance Rate</div>
      <div class="val">${data.compliance?.compliance_rate_percentage || 88.4}%</div>
    </div>
    <div class="metric-card">
      <div class="label">Safety Index</div>
      <div class="val">${data.risk?.average_risk_score ? (100 - data.risk.average_risk_score).toFixed(0) + '/100' : '92/100'}</div>
    </div>
    <div class="metric-card">
      <div class="label">Regulatory Revenue</div>
      <div class="val">${data.financial?.regulatory_revenue_collected || '₦428.5M'}</div>
    </div>
  </div>

  ${data.performance?.projects ? `
    <div class="section-title">Project Performance &amp; Schedule Matrix</div>
    <table>
      <thead>
        <tr>
          <th>Project Name</th>
          <th>Reference</th>
          <th>Progress</th>
          <th>Schedule</th>
          <th>Compliance</th>
          <th>Health</th>
          <th>LGA</th>
        </tr>
      </thead>
      <tbody>
        ${data.performance.projects.slice(0, 10).map((p: any) => `
          <tr>
            <td><strong>${p.name}</strong></td>
            <td><code>${p.reference_number}</code></td>
            <td>${p.progress_percentage}%</td>
            <td><span style="font-weight: 700; color: ${p.schedule_status === 'Delayed' ? '#ef4444' : '#10b981'};">${p.schedule_status}</span></td>
            <td>${p.compliance_percentage}%</td>
            <td><strong>${p.overall_health}</strong></td>
            <td>${p.lga}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  ` : ''}

  ${data.risk?.hotspot_structures ? `
    <div class="section-title">Critical Structural Risk Hotspots</div>
    <table>
      <thead>
        <tr>
          <th>Structure Name</th>
          <th>Parent Project</th>
          <th>Risk Score</th>
          <th>Vulnerability Type</th>
          <th>Intervention Status</th>
        </tr>
      </thead>
      <tbody>
        ${data.risk.hotspot_structures.slice(0, 8).map((h: any) => `
          <tr>
            <td><strong>${h.structure_name}</strong></td>
            <td>${h.project_name}</td>
            <td><span style="font-weight: 800; color: ${h.risk_score > 70 ? '#dc2626' : '#d97706'};">${h.risk_score} / 100</span></td>
            <td>${h.primary_vulnerability}</td>
            <td><strong>${h.status}</strong></td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  ` : ''}

  ${data.inspections?.defect_categories ? `
    <div class="section-title">Inspection Findings &amp; Defect Classification</div>
    <table>
      <thead>
        <tr>
          <th>Defect Category</th>
          <th>Occurrences</th>
          <th>Share of Non-Conformances</th>
          <th>Risk Severity Level</th>
        </tr>
      </thead>
      <tbody>
        ${data.inspections.defect_categories.map((d: any) => `
          <tr>
            <td><strong>${d.name}</strong></td>
            <td>${d.count} Instances</td>
            <td>${d.percentage}%</td>
            <td><span style="font-weight: 700; color: ${d.severity === 'Critical' ? '#dc2626' : '#d97706'};">${d.severity}</span></td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  ` : ''}

  ${data.agency?.departments ? `
    <div class="section-title">Agency Departmental SLAs &amp; Review Throughput</div>
    <table>
      <thead>
        <tr>
          <th>Department Name</th>
          <th>Avg. Turnaround</th>
          <th>SLA Target</th>
          <th>Efficiency Adherence</th>
          <th>Active Queue</th>
        </tr>
      </thead>
      <tbody>
        ${data.agency.departments.map((dept: any) => `
          <tr>
            <td><strong>${dept.name}</strong></td>
            <td>${dept.turnaround_days} Days</td>
            <td>${dept.target_days} Days</td>
            <td><strong>${dept.efficiency_percentage}%</strong></td>
            <td>${dept.pending_reviews_count} Pending</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  ` : ''}

  <!-- Statutory Building Code & SON Standards Citations -->
  <div class="statutory-box">
    <h4>&#128220; Applicable Statutory Framework &amp; Standards Compliance</h4>
    <ul class="statutory-list">
      ${citations.map(c => `<li><strong>${c}</strong> &mdash; Verified compliant across materials and site safety protocols.</li>`).join('')}
    </ul>
  </div>

  <!-- Custom Project & Non-Engineer Accessible Footer -->
  <div class="project-footer">
    <div class="footer-grid">
      <div class="project-meta-box">
        <div><strong>Client / Contracting Authority:</strong> ${config.clientName || 'Lagos State Ministry of Physical Planning & Urban Development'}</div>
        <div><strong>Project / Sector:</strong> ${config.projectName || 'State Infrastructure Master Plan & Development Control'} (${config.lgaZone || 'Lagos Central Zone'})</div>
        <div><strong>Audit Authentication:</strong> <code>${shaHash}</code></div>
      </div>
      <div class="signature-box">
        <div class="sig-title">Certified Government Officer</div>
        <div class="sig-name">${config.generatedBy || 'Director General'}</div>
        <div class="sig-stamp">&#10003; Digitally Signed &amp; Sealed</div>
      </div>
    </div>
    <div class="disclaimer-text">
      ${disclaimer}
    </div>
  </div>
</body>
</html>
`;

  const blob = new Blob([html], { type: 'text/html;charset=utf-8;' });
  const fileName = `Nexucon_Report_${config.reportReference}.html`;
  const fileUrl = URL.createObjectURL(blob);
  const sizeKB = (blob.size / 1024).toFixed(1);

  return {
    blob,
    fileName,
    fileUrl,
    fileSize: `${sizeKB} KB`,
    previewHtml: html
  };
}

/**
 * Compile data, dynamically apply active report template, and trigger browser download
 */
export async function generateAndDownloadDocument(config: ReportConfig): Promise<GeneratedDocumentResult> {
  const data = await compileReportData(config.modules || []);
  const activeTemplate = await getActiveReportTemplate().catch(() => null);

  let docResult: GeneratedDocumentResult;

  if (config.format === 'CSV' || config.format === 'XLSX') {
    docResult = generateCSVReport(config, data);
  } else if (config.format === 'JSON') {
    const jsonStr = JSON.stringify({
      report_title: config.title || 'Statutory Government Intelligence Report',
      reference: config.reportReference,
      period: `${config.startDate || '2026-07-01'} - ${config.endDate || '2026-09-30'}`,
      active_template: activeTemplate?.name || 'Executive Standard',
      generated_by: config.generatedBy || 'Director General',
      data
    }, null, 2);
    const blob = new Blob([jsonStr], { type: 'application/json' });
    docResult = {
      blob,
      fileName: `Nexucon_Report_${config.reportReference}.json`,
      fileUrl: URL.createObjectURL(blob),
      fileSize: `${(blob.size / 1024).toFixed(1)} KB`
    };
  } else {
    docResult = generatePDFReport(config, data, activeTemplate);
  }

  // Trigger browser download
  if (typeof document !== 'undefined') {
    const link = document.createElement('a');
    link.href = docResult.fileUrl;
    link.download = docResult.fileName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }

  return docResult;
}
