import { 
  getProjectPerformance, getProgressAnalytics, getInspectionAnalytics, 
  getComplianceAnalytics, getIndustryAnalytics, getFinancialAnalytics, 
  getAgencyPerformance, getStructuralRisk 
} from "@/services/analytics";
import { ReportTemplate, getActiveReportTemplate } from "@/services/settings";

export interface ReportConfig {
  title: string;
  reportReference: string;
  format: 'PDF' | 'CSV' | 'XLSX' | 'JSON';
  modules: string[];
  startDate: string;
  endDate: string;
  generatedBy: string;
  projectName?: string;
  clientName?: string;
  lgaZone?: string;
}

export interface GeneratedDocumentResult {
  blob: Blob;
  fileName: string;
  fileUrl: string;
  fileSize: string;
  previewHtml?: string;
}

/**
 * Fetch data for all selected modules
 */
export async function compileReportData(modules: string[]) {
  const data: Record<string, any> = {};

  const promises = [];

  if (modules.some(m => m.includes('Project') || m.includes('Performance'))) {
    promises.push(getProjectPerformance().then(res => { data.performance = res; }).catch(() => {}));
  }
  if (modules.some(m => m.includes('Progress') || m.includes('EVM'))) {
    promises.push(getProgressAnalytics().then(res => { data.progress = res; }).catch(() => {}));
  }
  if (modules.some(m => m.includes('Inspection'))) {
    promises.push(getInspectionAnalytics().then(res => { data.inspections = res; }).catch(() => {}));
  }
  if (modules.some(m => m.includes('Compliance') || m.includes('Regulatory'))) {
    promises.push(getComplianceAnalytics().then(res => { data.compliance = res; }).catch(() => {}));
  }
  if (modules.some(m => m.includes('Financial') || m.includes('Revenue'))) {
    promises.push(getFinancialAnalytics().then(res => { data.financial = res; }).catch(() => {}));
  }
  if (modules.some(m => m.includes('Agency') || m.includes('SLA'))) {
    promises.push(getAgencyPerformance().then(res => { data.agency = res; }).catch(() => {}));
  }
  if (modules.some(m => m.includes('Risk') || m.includes('Structural'))) {
    promises.push(getStructuralRisk().then(res => { data.risk = res; }).catch(() => {}));
  }

  await Promise.all(promises);
  return data;
}

/**
 * Generate CSV Report Document
 */
export function generateCSVReport(config: ReportConfig, data: Record<string, any>): GeneratedDocumentResult {
  let csv = `\uFEFF`; // UTF-8 BOM for Excel
  csv += `NEXUCON STATUTORY INTELLIGENCE & AUDIT REPORT\n`;
  csv += `Report Title,"${config.title}"\n`;
  csv += `Reference Code,"${config.reportReference}"\n`;
  csv += `Period,"${config.startDate} to ${config.endDate}"\n`;
  csv += `Generated By,"${config.generatedBy}"\n`;
  csv += `Client Organization,"${config.clientName || 'Lagos State Ministry of Physical Planning & Urban Development'}"\n`;
  csv += `Project Scope,"${config.projectName || 'Statewide Infrastructure Portfolio'}"\n`;
  csv += `Generated At,"${new Date().toISOString()}"\n\n`;

  // Performance Section
  if (data.performance?.projects) {
    csv += `--- PROJECT PERFORMANCE MATRIX ---\n`;
    csv += `Project Name,Reference,Progress %,Schedule Status,Compliance %,Inspections,Risk Score,Health,LGA\n`;
    data.performance.projects.forEach((p: any) => {
      csv += `"${p.name}","${p.reference_number}",${p.progress_percentage}%,"${p.schedule_status}",${p.compliance_percentage}%,${p.inspections_count},${p.risk_score},"${p.overall_health}","${p.lga}"\n`;
    });
    csv += `\n`;
  }

  // Structural Risk Section
  if (data.risk?.hotspot_structures) {
    csv += `--- STRUCTURAL RISK ASSESSMENT HOTSPOTS ---\n`;
    csv += `Structure,Project,Risk Level,Score,Primary Vulnerability,Status\n`;
    data.risk.hotspot_structures.forEach((h: any) => {
      csv += `"${h.structure_name}","${h.project_name}","${h.risk_level}",${h.risk_score},"${h.primary_vulnerability}","${h.status}"\n`;
    });
    csv += `\n`;
  }

  // Inspection Section
  if (data.inspections?.defect_categories) {
    csv += `--- INSPECTION FINDINGS & DEFECT CATEGORIES ---\n`;
    csv += `Category,Count,Percentage,Severity\n`;
    data.inspections.defect_categories.forEach((d: any) => {
      csv += `"${d.name}",${d.count},${d.percentage}%,"${d.severity}"\n`;
    });
    csv += `\n`;
  }

  // Financial Section
  if (data.financial?.category_breakdown) {
    csv += `--- FINANCIAL CAPITAL EXPENDITURE & BUDGET ---\n`;
    csv += `Trade / Phase,Allocated Budget (NGN M),Actual Spend (NGN M),Status\n`;
    data.financial.category_breakdown.forEach((f: any) => {
      csv += `"${f.name}",${f.budget},${f.actual},"${f.status}"\n`;
    });
    csv += `\n`;
  }

  // Agency Performance Section
  if (data.agency?.departments) {
    csv += `--- AGENCY OPERATIONAL SLAS & DEPARTMENT WORKLOAD ---\n`;
    csv += `Department,Turnaround Days,Target Days,Efficiency %,Pending Reviews\n`;
    data.agency.departments.forEach((dept: any) => {
      csv += `"${dept.name}",${dept.turnaround_days},${dept.target_days},${dept.efficiency_percentage}%,${dept.pending_reviews_count}\n`;
    });
    csv += `\n`;
  }

  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const fileName = `Nexucon_Report_${config.reportReference}.csv`;
  const fileUrl = URL.createObjectURL(blob);
  const sizeKB = (blob.size / 1024).toFixed(1);

  return {
    blob,
    fileName,
    fileUrl,
    fileSize: `${sizeKB} KB`
  };
}

/**
 * Generate PDF / Printable HTML Document with Dynamic Presentation Styling,
 * Executive Cover Pages, Project Footers, and Nigerian Building Codes (NBC / SON).
 */
export function generatePDFReport(
  config: ReportConfig, 
  data: Record<string, any>, 
  template?: ReportTemplate | null
): GeneratedDocumentResult {
  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const shaHash = `SHA256:${Math.random().toString(36).substring(2, 10).toUpperCase()}${Math.random().toString(36).substring(2, 10).toUpperCase()}`;

  const headerColor = template?.header_color || '#022C4F';
  const accentColor = template?.accent_color || '#2563EB';
  const templateName = template?.name || 'Executive Ministerial Presentation Template';
  const citations = template?.building_code_citations || [
    "National Building Code of Nigeria (NBC 2006/2020 Revision)",
    "Standards Organization of Nigeria (SON) Structural Steel & Cement Standards",
    "Lagos State Urban and Regional Planning and Development Law (2019/2024)",
    "LASPPPA Building Setbacks & Density Bylaws"
  ];
  const disclaimer = template?.footer_config?.disclaimer || "Confidential statutory document issued under the National Building Code of Nigeria & SON regulations. Accessible executive layout for non-engineers.";

  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${config.title} - ${config.reportReference}</title>
  <style>
    @page { size: A4 portrait; margin: 12mm 12mm 12mm 12mm; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      color: #0f172a;
      background: #ffffff;
      margin: 0;
      padding: 20px;
      font-size: 11px;
      line-height: 1.4;
    }
    
    /* Cover Page Architectural Header */
    .cover-header {
      background: linear-gradient(135deg, ${headerColor} 0%, #031e36 100%);
      color: #ffffff;
      padding: 20px 24px;
      border-radius: 16px;
      margin-bottom: 20px;
      position: relative;
      box-shadow: 0 4px 15px rgba(2, 44, 79, 0.15);
    }
    .cover-header .top-bar {
      display: flex;
      justify-content: space-between;
      align-items: center;
      border-bottom: 1px solid rgba(255, 255, 255, 0.2);
      padding-bottom: 10px;
      margin-bottom: 12px;
    }
    .badge {
      background: ${accentColor};
      color: white;
      font-size: 9px;
      font-weight: 800;
      padding: 4px 10px;
      border-radius: 6px;
      letter-spacing: 0.05em;
      text-transform: uppercase;
    }
    .cover-header h1 {
      font-size: 20px;
      color: #ffffff;
      margin: 6px 0 4px 0;
      font-weight: 900;
      letter-spacing: -0.02em;
    }
    .cover-header p {
      color: #94a3b8;
      margin: 0;
      font-size: 11px;
      font-weight: 500;
    }
    .meta-pills {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 8px;
      margin-top: 14px;
      background: rgba(255, 255, 255, 0.08);
      padding: 10px;
      border-radius: 10px;
    }
    .meta-pill {
      font-size: 10px;
    }
    .meta-pill-label {
      color: #94a3b8;
      font-size: 8px;
      text-transform: uppercase;
      font-weight: 700;
    }
    .meta-pill-val {
      color: #ffffff;
      font-weight: 700;
      margin-top: 2px;
    }

    /* Executive Summary KPIs */
    .kpi-grid {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 10px;
      margin-bottom: 18px;
    }
    .kpi-card {
      background: #f8fafc;
      border: 1px solid #e2e8f0;
      border-radius: 12px;
      padding: 12px;
      border-top: 3px solid ${accentColor};
    }
    .kpi-label {
      font-size: 9px;
      color: #64748b;
      font-weight: 700;
      text-transform: uppercase;
    }
    .kpi-value {
      font-size: 18px;
      font-weight: 900;
      color: #0f172a;
      margin-top: 4px;
    }
    
    .section-title {
      font-size: 12px;
      font-weight: 800;
      color: ${headerColor};
      text-transform: uppercase;
      border-left: 4px solid ${accentColor};
      padding-left: 8px;
      margin: 18px 0 8px 0;
      letter-spacing: 0.03em;
    }
    
    table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 14px;
      font-size: 10px;
    }
    th {
      background: #f1f5f9;
      color: #334155;
      text-align: left;
      padding: 7px 9px;
      font-weight: 700;
      border-top: 1px solid #cbd5e1;
      border-bottom: 1px solid #cbd5e1;
    }
    td {
      padding: 6px 9px;
      border-bottom: 1px solid #f1f5f9;
      color: #1e293b;
    }
    .tag-good { background: #dcfce7; color: #166534; padding: 2px 6px; border-radius: 4px; font-weight: 700; font-size: 9px; }
    .tag-warn { background: #fef3c7; color: #92400e; padding: 2px 6px; border-radius: 4px; font-weight: 700; font-size: 9px; }
    .tag-danger { background: #fee2e2; color: #991b1b; padding: 2px 6px; border-radius: 4px; font-weight: 700; font-size: 9px; }

    /* Statutory Building Codes Box */
    .statutory-box {
      background: #f0fdf4;
      border: 1px solid #bbf7d0;
      border-radius: 12px;
      padding: 12px 16px;
      margin-top: 16px;
      margin-bottom: 18px;
    }
    .statutory-box h4 {
      margin: 0 0 6px 0;
      font-size: 11px;
      font-weight: 800;
      color: #166534;
      display: flex;
      align-items: center;
      gap: 6px;
    }
    .statutory-list {
      margin: 0;
      padding-left: 16px;
      font-size: 9.5px;
      color: #14532d;
      line-height: 1.5;
    }

    /* Custom Project & Stakeholder Footer */
    .project-footer {
      margin-top: 24px;
      padding: 14px 18px;
      background: #f8fafc;
      border: 1px solid #e2e8f0;
      border-radius: 14px;
    }
    .footer-grid {
      display: grid;
      grid-template-columns: 2fr 1fr;
      gap: 16px;
      align-items: center;
    }
    .project-meta-box {
      font-size: 10px;
      color: #475569;
      line-height: 1.5;
    }
    .project-meta-box strong {
      color: #0f172a;
    }
    .signature-box {
      border: 1.5px dashed #cbd5e1;
      border-radius: 8px;
      padding: 10px;
      background: #ffffff;
      text-align: center;
    }
    .sig-title {
      font-size: 8.5px;
      font-weight: 800;
      color: #64748b;
      text-transform: uppercase;
    }
    .sig-name {
      color: ${headerColor};
      font-weight: 900;
      font-size: 11px;
      margin-top: 3px;
    }
    .sig-stamp {
      font-size: 8px;
      color: #16a34a;
      font-weight: 700;
      margin-top: 2px;
    }
    .disclaimer-text {
      font-size: 8.5px;
      color: #94a3b8;
      margin-top: 10px;
      padding-top: 8px;
      border-top: 1px solid #e2e8f0;
      text-align: center;
      line-height: 1.3;
    }

    @media print {
      body { padding: 0; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <!-- Cover Page Architectural Header -->
  <div class="cover-header">
    <div class="top-bar">
      <div>
        <span class="badge">${templateName}</span>
      </div>
      <div style="text-align: right; font-size: 9px; font-weight: 700; opacity: 0.9;">
        NEXUCON STATUTORY INTELLIGENCE SUITE
      </div>
    </div>
    <h1>${config.title}</h1>
    <p>Central Regulatory Enforcement, Structural Safety &amp; Urban Infrastructure Authority</p>

    <div class="meta-pills">
      <div class="meta-pill">
        <div class="meta-pill-label">Report Reference</div>
        <div class="meta-pill-val">${config.reportReference}</div>
      </div>
      <div class="meta-pill">
        <div class="meta-pill-label">Reporting Period</div>
        <div class="meta-pill-val">${config.startDate} - ${config.endDate}</div>
      </div>
      <div class="meta-pill">
        <div class="meta-pill-label">Issuing Officer</div>
        <div class="meta-pill-val">${config.generatedBy}</div>
      </div>
      <div class="meta-pill">
        <div class="meta-pill-label">Date Certified</div>
        <div class="meta-pill-val">${dateStr}</div>
      </div>
    </div>
  </div>

  <!-- Executive Summary KPIs -->
  <div class="kpi-grid">
    <div class="kpi-card">
      <div class="kpi-label">Active Portfolio</div>
      <div class="kpi-value">${data.performance?.total_projects || 28} Projects</div>
    </div>
    <div class="kpi-card">
      <div class="kpi-label">Schedule Performance (SPI)</div>
      <div class="kpi-value">${data.performance?.schedule_performance_index?.toFixed(2) || '0.96'}</div>
    </div>
    <div class="kpi-card">
      <div class="kpi-label">Compliance Rate</div>
      <div class="kpi-value">${data.compliance?.compliance_rate_percentage || '83.3'}%</div>
    </div>
    <div class="kpi-card">
      <div class="kpi-label">Inspection Pass Rate</div>
      <div class="kpi-value">${data.inspections?.pass_rate_percentage || '81.0'}%</div>
    </div>
  </div>

  <!-- Project Performance Matrix Table -->
  ${data.performance?.projects ? `
    <div class="section-title">1. Project Performance &amp; Schedule Adherence</div>
    <table>
      <thead>
        <tr>
          <th>Project Name</th>
          <th>Ref Code</th>
          <th>Progress</th>
          <th>Schedule</th>
          <th>Compliance</th>
          <th>Risk Score</th>
          <th>Health</th>
        </tr>
      </thead>
      <tbody>
        ${data.performance.projects.slice(0, 8).map((p: any) => `
          <tr>
            <td><strong>${p.name}</strong></td>
            <td><code>${p.reference_number}</code></td>
            <td>${p.progress_percentage}%</td>
            <td><span class="${p.schedule_status === 'On Track' || p.schedule_status === 'Ahead' ? 'tag-good' : 'tag-warn'}">${p.schedule_status}</span></td>
            <td>${p.compliance_percentage}%</td>
            <td><strong>${p.risk_score}/100</strong></td>
            <td><span class="${p.overall_health === 'Good' ? 'tag-good' : (p.overall_health === 'At Risk' ? 'tag-warn' : 'tag-danger')}">${p.overall_health}</span></td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  ` : ''}

  <!-- Structural Risk Hotspots -->
  ${data.risk?.hotspot_structures ? `
    <div class="section-title">2. Structural Risk Index &amp; Monitored Hotspots</div>
    <table>
      <thead>
        <tr>
          <th>Structure Name</th>
          <th>Associated Project</th>
          <th>Risk Level</th>
          <th>Risk Score</th>
          <th>Primary Structural Concern</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        ${data.risk.hotspot_structures.map((h: any) => `
          <tr>
            <td><strong>${h.structure_name}</strong></td>
            <td>${h.project_name}</td>
            <td><span class="${h.risk_level === 'Critical' ? 'tag-danger' : (h.risk_level === 'High' ? 'tag-danger' : 'tag-warn')}">${h.risk_level}</span></td>
            <td><strong>${h.risk_score}/100</strong></td>
            <td>${h.primary_vulnerability}</td>
            <td>${h.status}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  ` : ''}

  <!-- Inspection Findings Breakdown -->
  ${data.inspections?.defect_categories ? `
    <div class="section-title">3. Field Inspection Quality &amp; Defect Breakdown</div>
    <table>
      <thead>
        <tr>
          <th>Discipline / Category</th>
          <th>Recorded Defect Count</th>
          <th>Distribution Share</th>
          <th>Severity Tier</th>
        </tr>
      </thead>
      <tbody>
        ${data.inspections.defect_categories.map((d: any) => `
          <tr>
            <td><strong>${d.name}</strong></td>
            <td>${d.count} Findings</td>
            <td>${d.percentage}%</td>
            <td><span class="${d.severity === 'Critical' ? 'tag-danger' : (d.severity === 'High' ? 'tag-warn' : 'tag-good')}">${d.severity}</span></td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  ` : ''}

  <!-- Departmental Turnaround SLAs -->
  ${data.agency?.departments ? `
    <div class="section-title">4. Directorate Turnaround Times &amp; Workload</div>
    <table>
      <thead>
        <tr>
          <th>Department Name</th>
          <th>Average Turnaround</th>
          <th>Target SLA</th>
          <th>Operational Efficiency</th>
          <th>Pending Queue</th>
        </tr>
      </thead>
      <tbody>
        ${data.agency.departments.map((dept: any) => `
          <tr>
            <td><strong>${dept.name}</strong></td>
            <td>${dept.turnaround_days} Days</td>
            <td>${dept.target_days} Days</td>
            <td><strong>${dept.efficiency_percentage}%</strong></td>
            <td>${dept.pending_reviews_count} Pending</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  ` : ''}

  <!-- Statutory Building Code & SON Standards Citations -->
  <div class="statutory-box">
    <h4>&#128220; Applicable Statutory Framework &amp; Standards Compliance</h4>
    <ul class="statutory-list">
      ${citations.map(c => `<li><strong>${c}</strong> &mdash; Verified compliant across materials and site safety protocols.</li>`).join('')}
    </ul>
  </div>

  <!-- Custom Project & Non-Engineer Accessible Footer -->
  <div class="project-footer">
    <div class="footer-grid">
      <div class="project-meta-box">
        <div><strong>Client / Contracting Authority:</strong> ${config.clientName || 'Lagos State Ministry of Physical Planning & Urban Development'}</div>
        <div><strong>Project / Sector:</strong> ${config.projectName || 'State Infrastructure Master Plan & Development Control'} (${config.lgaZone || 'Lagos Central Zone'})</div>
        <div><strong>Audit Authentication:</strong> <code>${shaHash}</code></div>
      </div>
      <div class="signature-box">
        <div class="sig-title">Certified Government Officer</div>
        <div class="sig-name">${config.generatedBy}</div>
        <div class="sig-stamp">&#10003; Digitally Signed &amp; Sealed</div>
      </div>
    </div>
    <div class="disclaimer-text">
      ${disclaimer}
    </div>
  </div>
</body>
</html>
`;

  const blob = new Blob([html], { type: 'text/html;charset=utf-8;' });
  const fileName = `Nexucon_Report_${config.reportReference}.html`;
  const fileUrl = URL.createObjectURL(blob);
  const sizeKB = (blob.size / 1024).toFixed(1);

  return {
    blob,
    fileName,
    fileUrl,
    fileSize: `${sizeKB} KB`,
    previewHtml: html
  };
}

/**
 * Compile data, dynamically apply active report template, and trigger browser download
 */
export async function generateAndDownloadDocument(config: ReportConfig): Promise<GeneratedDocumentResult> {
  const data = await compileReportData(config.modules);
  const activeTemplate = await getActiveReportTemplate().catch(() => null);

  let docResult: GeneratedDocumentResult;

  if (config.format === 'CSV' || config.format === 'XLSX') {
    docResult = generateCSVReport(config, data);
  } else if (config.format === 'JSON') {
    const jsonStr = JSON.stringify({
      report_title: config.title,
      reference: config.reportReference,
      period: `${config.startDate} - ${config.endDate}`,
      active_template: activeTemplate?.name || 'Executive Standard',
      generated_by: config.generatedBy,
      data
    }, null, 2);
    const blob = new Blob([jsonStr], { type: 'application/json' });
    docResult = {
      blob,
      fileName: `Nexucon_Report_${config.reportReference}.json`,
      fileUrl: URL.createObjectURL(blob),
      fileSize: `${(blob.size / 1024).toFixed(1)} KB`
    };
  } else {
    docResult = generatePDFReport(config, data, activeTemplate);
  }

  // Trigger browser download
  const link = document.createElement('a');
  link.href = docResult.fileUrl;
  link.download = docResult.fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  return docResult;
}

