# Generated by Django 4.2.30 on 2026-08-14 01:29

import apps.documents.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='file_url',
        ),
        migrations.AddField(
            model_name='version',
            name='file',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/', validators=[apps.documents.validators.SecureFileValidator()]),
        ),
    ]
