# Generated by Django 4.2.30 on 2026-08-19 12:34

import apps.documents.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_project_applicable_regulations_project_approval_date_and_more'),
        ('documents', '0002_remove_version_file_url_version_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('PERMIT', 'Permits & Approvals'), ('INSPECTION', 'Site Inspections'), ('ENFORCEMENT', 'Enforcement & Stop-Work'), ('COMPLIANCE', 'Environmental & Compliance'), ('LEGAL', 'Contracts & Legal')], default='INSPECTION', max_length=50)),
                ('description', models.TextField()),
                ('file_format', models.CharField(default='PDF', max_length=20)),
                ('file_url', models.CharField(blank=True, default='https://ba64cd9c51c2da4db93a1886397fd7b3.r2.cloudflarestorage.com/nexucondocument/template.pdf', max_length=500, null=True)),
                ('file_size', models.CharField(default='450 KB', max_length=50)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='approval',
            options={'ordering': ['-reviewed_at']},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='approval',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='version',
            name='file',
        ),
        migrations.AddField(
            model_name='approval',
            name='approval_reference',
            field=models.CharField(blank=True, db_index=True, default=apps.documents.models.generate_app_ref, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='approved_by_name',
            field=models.CharField(default='Gov. Planning Comm.', max_length=255),
        ),
        migrations.AddField(
            model_name='approval',
            name='category',
            field=models.CharField(default='Project Planning', max_length=100),
        ),
        migrations.AddField(
            model_name='approval',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to='documents.document'),
        ),
        migrations.AddField(
            model_name='approval',
            name='signature_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='current_version',
            field=models.CharField(default='v1.0', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='discipline',
            field=models.CharField(choices=[('Architecture', 'Architecture'), ('Structural', 'Structural'), ('MEP', 'MEP (Mechanical/Electrical/Plumbing)'), ('Planning', 'Planning & Urban Design'), ('Legal', 'Contracts & Legal'), ('Environmental', 'Environmental & Geotechnical'), ('General', 'General / Administrative')], default='Architecture', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='document_reference',
            field=models.CharField(blank=True, db_index=True, default=apps.documents.models.generate_doc_ref, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_format',
            field=models.CharField(default='PDF', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.CharField(default='12.4 MB', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='file_url',
            field=models.CharField(blank=True, default='https://ba64cd9c51c2da4db93a1886397fd7b3.r2.cloudflarestorage.com/nexucondocument/sample.pdf', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.CharField(default='01_Architectural', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='is_digitally_stamped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='is_shared',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='pages_count',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='document',
            name='signature_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='stamp_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='stamped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='stamped_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('EXPIRING_SOON', 'Expiring Soon')], default='APPROVED', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='uploader_name',
            field=models.CharField(default='S. Jenkins', max_length=255),
        ),
        migrations.AddField(
            model_name='version',
            name='author_name',
            field=models.CharField(default='Lead Architect', max_length=255),
        ),
        migrations.AddField(
            model_name='version',
            name='author_role',
            field=models.CharField(default='Review Team', max_length=255),
        ),
        migrations.AddField(
            model_name='version',
            name='changes_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='file_size',
            field=models.CharField(default='12.4 MB', max_length=50),
        ),
        migrations.AddField(
            model_name='version',
            name='file_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='status',
            field=models.CharField(default='Current', max_length=50),
        ),
        migrations.AddField(
            model_name='version',
            name='version_label',
            field=models.CharField(default='v1.0', max_length=50),
        ),
        migrations.AlterField(
            model_name='approval',
            name='reviewed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=50),
        ),
        migrations.AlterField(
            model_name='approval',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='documents.version'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('DRAWING', '2D Architectural / Structural Drawing'), ('CONTRACT', 'Contract & Legal Agreement'), ('INSPECTION_REPORT', 'Site Inspection Report'), ('COMPLIANCE_CERTIFICATE', 'Compliance Certificate'), ('SITE_PHOTO', 'Site Photograph'), ('REPORT', 'Technical Report'), ('PERMIT_ATTACHMENT', 'Permit Submission Document')], default='DRAWING', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='version',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('files_count', models.IntegerField(default=0)),
                ('total_size', models.CharField(default='0 MB', max_length=50)),
                ('is_shared', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_folders', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
