# Generated by Django 4.2.30 on 2026-08-24 05:22

import apps.documents.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bim', '0003_alter_bimprogressvalidation_simulation_date'),
        ('approvals', '0001_initial'),
        ('inspections', '0002_alter_finding_options_alter_inspection_options_and_more'),
        ('compliance', '0002_alter_compliancecertificate_issue_date_and_more'),
        ('documents', '0003_documenttemplate_alter_approval_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='linked_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_documents', to='approvals.approvalrequest'),
        ),
        migrations.AddField(
            model_name='document',
            name='linked_bim_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_documents', to='bim.bimmodel'),
        ),
        migrations.AddField(
            model_name='document',
            name='linked_compliance_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_documents', to='compliance.nonconformancereport'),
        ),
        migrations.AddField(
            model_name='document',
            name='linked_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_documents', to='inspections.inspection'),
        ),
        migrations.AddField(
            model_name='version',
            name='signature_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='discipline',
            field=models.CharField(choices=[('Architecture', 'Architecture'), ('Structural', 'Structural'), ('MEP', 'MEP (Mechanical/Electrical/Plumbing)'), ('Planning', 'Planning & Urban Design'), ('Legal', 'Contracts & Legal'), ('Environmental', 'Environmental & Geotechnical'), ('Civil', 'Civil & Infrastructure'), ('General', 'General / Administrative')], default='Architecture', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('PROJECT_DOCUMENT', 'Project Document / Administrative'), ('SUBMITTED_DRAWING', 'Submitted 2D Drawing / Blueprint'), ('TECHNICAL_REPORT', 'Technical Engineering Report / Study'), ('COMPLIANCE_DOCUMENT', 'Statutory Compliance Document / Certificate'), ('INSPECTION_REPORT', 'Site Inspection & QA/QC Report'), ('APPROVAL_RECORD', 'Official Government Approval Record'), ('DRAWING', '2D Architectural / Structural Drawing'), ('CONTRACT', 'Contract & Legal Agreement'), ('COMPLIANCE_CERTIFICATE', 'Compliance Certificate'), ('SITE_PHOTO', 'Site Photograph'), ('REPORT', 'Technical Report'), ('PERMIT_ATTACHMENT', 'Permit Submission Document')], default='PROJECT_DOCUMENT', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('CHANGES_REQUESTED', 'Changes Requested'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('EXPIRING_SOON', 'Expiring Soon'), ('ARCHIVED', 'Archived')], default='APPROVED', max_length=50),
        ),
        migrations.CreateModel(
            name='DocumentReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_reference', models.CharField(db_index=True, default=apps.documents.models.generate_review_ref, max_length=100)),
                ('reviewer_name', models.CharField(default='Government Reviewer', max_length=255)),
                ('reviewer_role', models.CharField(default='Senior Plan Reviewer', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('CHANGES_REQUESTED', 'Changes Requested'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='documents.document')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_reviews', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='documents.version')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='System', max_length=255)),
                ('action', models.CharField(choices=[('UPLOAD', 'Document Uploaded'), ('VERSION_CREATED', 'New Revision Created'), ('STAMPED', 'Digitally Stamped'), ('REVIEWED', 'Document Reviewed'), ('DOWNLOADED', 'Document Downloaded'), ('ARCHIVED', 'Document Archived'), ('RESTORED', 'Document Restored'), ('LINKED', 'Cross-Module Linkage Added')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='documents.document')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_level', models.CharField(choices=[('VIEW', 'View Only'), ('EDIT', 'Edit & Revision'), ('STAMP', 'Digital Stamp & Approval'), ('ADMIN', 'Full Administrative Access')], default='VIEW', max_length=50)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to='documents.document')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('document', 'user')},
            },
        ),
    ]
