# Generated by Django 4.2.30 on 2026-08-19 09:40

import apps.permits.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0002_agency_city_agency_collaboration_preference_and_more'),
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permit',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='permit',
            name='last_renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permit',
            name='qr_verification_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='permit',
            name='renewal_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='permit',
            name='issue_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='permit',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_permits', to='government.profile'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='permit_number',
            field=models.CharField(default=apps.permits.models.generate_permit_number, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired'), ('RENEWED', 'Renewed')], default='ACTIVE', max_length=50),
        ),
    ]
