"use client";

import React, { useState, useEffect } from "react";
import Link from "next/link";
import {
  FileText,
  Download,
  RefreshCw,
  ClipboardCheck,
  ShieldAlert,
} from "lucide-react";
import {
  getInspectorInspections,
  downloadInspectorInspectionReport,
  describeBlobError,
} from "@/services/inspector";
import { Inspection } from "@/services/inspections";
import { orDash, dateOr } from "@/lib/display";

/**
 * Statutory reports, generated from the inspection records this inspector can
 * actually reach.
 *
 * This page used to render three hardcoded "reports" —
 * "Statutory Foundation Review Certificate #INS-2026-00412", a GPR scan report
 * "#GPR-88A1" and a UPV strength assessment — against "Lekki Pearl Residences"
 * and "Eko Atlantic Tower D". The titles, the reference numbers, the project
 * names, the dates and the "Official Signed" status were all literals, and the
 * "Download PDF" button on every row had no handler. Nothing on the page had
 * ever been generated by the platform.
 *
 * A report is not a stored object here: `GET /reports/inspections/{id}/report/`
 * renders one from the live inspection record on demand. So the honest index of
 * "reports" available to an inspector is the inspector's own inspections, each
 * with the report the server will produce for it. Where the record is thin, the
 * generated report says so itself — it prints "NOT RECORDED" rather than
 * inventing a value.
 */
export default function InspectorReportsPage() {
  const [inspections, setInspections] = useState<Inspection[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [busyId, setBusyId] = useState<string | null>(null);
  const [actionError, setActionError] = useState<string | null>(null);

  const fetchInspections = async () => {
    setIsLoading(true);
    setLoadError(null);
    try {
      const data = await getInspectorInspections();
      setInspections(Array.isArray(data) ? data : []);
    } catch (err: any) {
      setInspections([]);
      setLoadError(
        err?.response?.data?.detail ||
          err?.message ||
          "Could not reach the inspections service."
      );
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchInspections();
  }, []);

  const handleDownload = async (insp: Inspection) => {
    setBusyId(insp.id);
    setActionError(null);
    try {
      const blob = await downloadInspectorInspectionReport(insp.id);
      if (!(blob instanceof Blob) || blob.size === 0) {
        setActionError(
          "The server returned an empty response, so no report was saved."
        );
        return;
      }
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `inspection_${insp.inspection_reference || insp.id}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err: any) {
      setActionError(await describeBlobError(err));
    } finally {
      setBusyId(null);
    }
  };

  return (
    <div className="space-y-6 sm:space-y-8 animate-in fade-in duration-200 min-w-0">
      <div className="flex flex-col md:flex-row md:items-start justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-[#022C4F] flex items-center justify-center text-white shadow-md shrink-0">
            <FileText size={20} />
          </div>
          <div>
            <h1 className="text-2xl sm:text-3xl font-bold text-[#022C4F] leading-tight">
              Statutory Reports &amp; Certificates
            </h1>
            <p className="text-gray-600 text-xs sm:text-sm mt-0.5">
              Generate and export the signed statutory report the platform holds for each of your inspections.
            </p>
          </div>
        </div>

        <button
          type="button"
          onClick={fetchInspections}
          className="self-start md:self-auto p-2.5 rounded-xl border border-slate-200 bg-white hover:bg-slate-50 text-[#022C4F] transition-colors cursor-pointer shadow-sm"
          title="Refresh"
        >
          <RefreshCw size={15} className={isLoading ? "animate-spin" : ""} />
        </button>
      </div>

      {actionError && (
        <div className="p-4 rounded-2xl bg-rose-50 border border-rose-200 flex items-start gap-2.5">
          <ShieldAlert size={18} className="text-rose-600 shrink-0 mt-0.5" />
          <div className="text-xs text-rose-800">
            <div className="font-bold mb-0.5">The report was not produced</div>
            <p className="leading-relaxed">{actionError}</p>
          </div>
        </div>
      )}

      {isLoading ? (
        <div className="py-20 flex items-center justify-center">
          <div className="w-8 h-8 border-3 border-[#022C4F] border-t-transparent rounded-full animate-spin" />
        </div>
      ) : loadError ? (
        <div className="p-6 rounded-2xl bg-amber-50 border border-amber-200">
          <h3 className="text-sm font-bold text-amber-900 mb-1">
            Your inspections could not be read
          </h3>
          <p className="text-xs text-amber-800">{loadError}</p>
          <p className="text-xs text-amber-700 mt-2">
            No report is listed because no inspection record could be read. This
            is not a statement that you have no reports.
          </p>
        </div>
      ) : inspections.length === 0 ? (
        <div className="text-center py-20 bg-white border border-slate-200/80 rounded-2xl p-8 shadow-sm">
          <ClipboardCheck size={36} className="text-slate-400 mx-auto mb-3" />
          <h3 className="text-sm font-bold text-slate-800 mb-1">
            No Inspections To Report On
          </h3>
          <p className="text-xs text-slate-500 max-w-sm mx-auto">
            A statutory report is produced from an inspection record. None has
            been assigned to you yet, so there is nothing to generate.
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {inspections.map((insp) => (
            <div
              key={insp.id}
              className="p-5 rounded-2xl bg-white border border-slate-200/80 hover:border-slate-300 flex flex-col sm:flex-row sm:items-center justify-between gap-4 shadow-sm hover:shadow-md transition-all"
            >
              <div className="min-w-0">
                <div className="flex flex-wrap items-center gap-2 mb-1.5">
                  <span className="text-[11px] font-bold text-amber-800 bg-amber-50 px-2.5 py-0.5 rounded-full border border-amber-200">
                    {orDash(insp.inspection_type, "Type not recorded")}
                  </span>
                  <span className="text-[11px] font-semibold text-slate-700 bg-slate-100 px-2.5 py-0.5 rounded-full border border-slate-200">
                    {orDash(insp.status, "Status not recorded")}
                  </span>
                  {insp.checkin_time ? (
                    <span className="text-[11px] font-semibold text-emerald-800 bg-emerald-50 px-2.5 py-0.5 rounded-full border border-emerald-200">
                      Checked in {dateOr(insp.checkin_time)}
                    </span>
                  ) : (
                    <span className="text-[11px] font-semibold text-slate-500 bg-slate-50 px-2.5 py-0.5 rounded-full border border-slate-200">
                      Never checked in
                    </span>
                  )}
                </div>
                <h3 className="text-sm sm:text-base font-bold text-[#022C4F] truncate">
                  Statutory Inspection Report —{" "}
                  {orDash(insp.inspection_reference, "no reference")}
                </h3>
                <div className="text-xs text-slate-500 mt-1">
                  Project:{" "}
                  <strong className="text-slate-800 font-semibold">
                    {orDash(insp.project_name, "Not recorded")}
                  </strong>{" "}
                  &bull; Scheduled: {dateOr(insp.scheduled_date)}
                  {insp.completed_date
                    ? ` • Completed: ${dateOr(insp.completed_date)}`
                    : ""}
                </div>
              </div>

              <div className="flex items-center gap-2 shrink-0">
                <Link
                  href={`/inspector/dashboard/inspections/${insp.id}`}
                  className="px-3.5 py-2 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-semibold transition-colors cursor-pointer shadow-sm"
                >
                  Open Inspection
                </Link>
                <button
                  type="button"
                  onClick={() => handleDownload(insp)}
                  disabled={busyId === insp.id}
                  className="px-4 py-2 rounded-xl bg-[#022C4F] hover:bg-[#022C4F]/90 text-white text-xs font-semibold transition-all flex items-center gap-1.5 cursor-pointer shadow-sm disabled:opacity-60"
                >
                  {busyId === insp.id ? (
                    <div className="w-3.5 h-3.5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                  ) : (
                    <Download size={14} />
                  )}
                  <span>{busyId === insp.id ? "Generating…" : "Download PDF"}</span>
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
