# Generated by Django 4.2.30 on 2026-08-20 02:41

import apps.settings.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeyCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('key_prefix', models.CharField(default='nx_live_', max_length=50)),
                ('hashed_key', models.CharField(max_length=255)),
                ('app_type', models.CharField(default='OAuth 2.0 App', max_length=100)),
                ('volume_tier', models.CharField(default='High (450k/day)', max_length=100)),
                ('status', models.CharField(default='Healthy', max_length=50)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BIMIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='Connected', max_length=50)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('synced_models_count', models.IntegerField(default=0)),
                ('webhook_url', models.CharField(blank=True, max_length=500, null=True)),
                ('icon_code', models.CharField(default='A', max_length=10)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['provider'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSystemIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('system_type', models.CharField(default='Cloud Storage', max_length=100)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('bucket_or_drive_name', models.CharField(default='nexucondocument', max_length=255)),
                ('endpoint_url', models.CharField(default='https://ba64cd9c51c2da4db93a1886397fd7b3.r2.cloudflarestorage.com/nexucondocument', max_length=500)),
                ('synced_files_count', models.IntegerField(default=0)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GovernmentAPIIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_key_identifier', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('endpoint_url', models.CharField(max_length=500)),
                ('status', models.CharField(default='connected', max_length=50)),
                ('data_flow_direction', models.CharField(default='Bidirectional', max_length=50)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_reference', models.CharField(db_index=True, default=apps.settings.models.generate_log_id, max_length=100)),
                ('service_name', models.CharField(max_length=255)),
                ('event_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='Success', max_length=50)),
                ('payload_size', models.CharField(default='2.4 MB', max_length=50)),
                ('http_status_code', models.IntegerField(default=200)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TersusDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, default=apps.settings.models.generate_dev_id, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('device_type', models.CharField(default='RTK Receiver', max_length=100)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('battery_level', models.CharField(default='98%', max_length=50)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(default=6.5244)),
                ('longitude', models.FloatField(default=3.3792)),
                ('firmware_version', models.CharField(default='v2.4.1', max_length=50)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
