# Generated by Django 4.2.30 on 2026-08-20 03:08

import apps.settings.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.CharField(default=apps.settings.models.generate_wf_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('System Enforced', 'System Enforced'), ('Draft', 'Draft'), ('Archived', 'Archived')], default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceStandard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('num_value', models.FloatField(default=0.0)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('alert_level', models.CharField(default='Warning', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('role_type', models.CharField(default='Custom Role', max_length=50)),
                ('is_system_default', models.BooleanField(default=False)),
                ('active_users_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InspectionTemplate',
            fields=[
                ('id', models.CharField(default=apps.settings.models.generate_tpl_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(default='Structural', max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Draft', 'Draft'), ('Archived', 'Archived')], default='Active', max_length=50)),
                ('version', models.CharField(default='v1.0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRoutingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_event', models.CharField(max_length=255)),
                ('primary_recipient', models.CharField(max_length=255)),
                ('sla_timeline', models.CharField(default='Within 15 mins', max_length=100)),
                ('escalation_target', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatutoryDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('connected_features', models.JSONField(default=list)),
                ('document_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('target_url', models.CharField(max_length=500)),
                ('events', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Paused', 'Paused'), ('Failing', 'Failing')], default='Active', max_length=50)),
                ('secret_token', models.CharField(default=uuid.uuid4, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(default='Urban Planning', max_length=255)),
                ('role', models.CharField(default='Reviewer', max_length=100)),
                ('token', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Revoked', 'Revoked'), ('Expired', 'Expired')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_staff_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreferenceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('event_label', models.CharField(max_length=255)),
                ('in_app', models.BooleanField(default=True)),
                ('email', models.BooleanField(default=True)),
                ('sms', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['category', 'event_label'],
                'unique_together': {('category', 'event_label')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_order', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=500)),
                ('field_type', models.CharField(choices=[('Number Input', 'Number Input'), ('Pass/Fail Toggle', 'Pass/Fail Toggle'), ('Photo Upload', 'Photo Upload'), ('Text Input', 'Text Input')], default='Pass/Fail Toggle', max_length=100)),
                ('is_required', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='settings.inspectiontemplate')),
            ],
            options={
                'ordering': ['template', 'item_order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_order', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('icon_name', models.CharField(default='ShieldCheck', max_length=100)),
                ('is_system_enforced', models.BooleanField(default=False)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='settings.approvalworkflow')),
            ],
            options={
                'ordering': ['workflow', 'step_order'],
                'unique_together': {('workflow', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=100)),
                ('permission_name', models.CharField(max_length=255)),
                ('is_granted', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='settings.customrole')),
            ],
            options={
                'ordering': ['module', 'permission_name'],
                'unique_together': {('role', 'module', 'permission_name')},
            },
        ),
    ]
