# Generated by Django 4.2.30 on 2026-08-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_approvalworkflow_compliancestandard_customrole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeycredential',
            name='allowed_ips',
            field=models.CharField(default='*', max_length=255),
        ),
        migrations.AddField(
            model_name='apikeycredential',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apikeycredential',
            name='rate_limit_per_min',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='apikeycredential',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bimintegration',
            name='environment',
            field=models.CharField(default='Production', max_length=50),
        ),
        migrations.AddField(
            model_name='bimintegration',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bimintegration',
            name='last_successful_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bimintegration',
            name='project_count',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='documentsystemintegration',
            name='encrypted_secret_preview',
            field=models.CharField(default='••••••••••••8A72', max_length=100),
        ),
        migrations.AddField(
            model_name='documentsystemintegration',
            name='folder_count',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='documentsystemintegration',
            name='storage_provider',
            field=models.CharField(default='Cloudflare R2', max_length=100),
        ),
        migrations.AddField(
            model_name='governmentapiintegration',
            name='auth_method',
            field=models.CharField(default='mTLS / Bearer Token', max_length=100),
        ),
        migrations.AddField(
            model_name='governmentapiintegration',
            name='credential_status',
            field=models.CharField(default='ACTIVE', max_length=50),
        ),
        migrations.AddField(
            model_name='governmentapiintegration',
            name='documentation_status',
            field=models.CharField(default='PENDING CLIENT API DOCUMENTATION/CREDENTIALS', max_length=100),
        ),
        migrations.AddField(
            model_name='governmentapiintegration',
            name='provider_code',
            field=models.CharField(default='CAC', max_length=50),
        ),
        migrations.AddField(
            model_name='integrationlog',
            name='direction',
            field=models.CharField(default='Inbound', max_length=50),
        ),
        migrations.AddField(
            model_name='integrationlog',
            name='duration_ms',
            field=models.IntegerField(default=142),
        ),
        migrations.AddField(
            model_name='integrationlog',
            name='error_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='integrationlog',
            name='request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tersusdevice',
            name='coordinate_system',
            field=models.CharField(default='WGS84 / Minna Datum UTM Zone 31N', max_length=100),
        ),
        migrations.AddField(
            model_name='tersusdevice',
            name='elevation',
            field=models.FloatField(default=12.45),
        ),
        migrations.AddField(
            model_name='tersusdevice',
            name='horizontal_accuracy',
            field=models.CharField(default='0.008 m', max_length=50),
        ),
        migrations.AddField(
            model_name='tersusdevice',
            name='rtk_fix_status',
            field=models.CharField(default='FIXED_RTK', max_length=50),
        ),
        migrations.AddField(
            model_name='tersusdevice',
            name='satellites_tracked',
            field=models.IntegerField(default=28),
        ),
        migrations.AddField(
            model_name='tersusdevice',
            name='vertical_accuracy',
            field=models.CharField(default='0.015 m', max_length=50),
        ),
    ]
