# Generated by Django 4.2.30 on 2026-08-27 03:08

import apps.settings.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_apikeycredential_allowed_ips_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agency_name', models.CharField(default='Lagos State Ministry of Physical Planning & Urban Development (MPP&UD)', max_length=255)),
                ('agency_code', models.CharField(default='LASG-MPPUD-01', max_length=100, unique=True)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(default='Central Statutory Enforcement, Development Control, and Building Clearance Authority.')),
                ('government_level', models.CharField(default='State', max_length=50)),
                ('jurisdiction', models.CharField(default='Lagos State, Federal Republic of Nigeria', max_length=255)),
                ('official_email', models.EmailField(default='planning@lagosstate.gov.ng', max_length=254)),
                ('phone', models.CharField(default='+234 1 234 5678', max_length=100)),
                ('website', models.CharField(default='https://mppud.lagosstate.gov.ng', max_length=255)),
                ('office_address', models.CharField(default='Block 15, The Secretariat, Alausa, Ikeja, Lagos', max_length=500)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('state', models.CharField(default='Lagos State', max_length=100)),
                ('lga', models.CharField(default='Ikeja', max_length=100)),
                ('timezone', models.CharField(default='Africa/Lagos (GMT+1)', max_length=100)),
                ('default_language', models.CharField(default='English (NG)', max_length=100)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['agency_name'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.CharField(default=apps.settings.models.generate_rpt_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('theme_style', models.CharField(default='Executive Vibrant', max_length=100)),
                ('cover_page_style', models.CharField(default='Detailed Architectural Hero', max_length=100)),
                ('header_color', models.CharField(default='#022C4F', max_length=50)),
                ('accent_color', models.CharField(default='#2563EB', max_length=50)),
                ('footer_config', models.JSONField(default=dict)),
                ('building_code_citations', models.JSONField(default=list)),
                ('preview_thumbnail_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active_default', 'name'],
            },
        ),
    ]
