# Generated by Django 4.2.30 on 2026-08-19 12:42

import apps.compliance.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_applicable_regulations_project_approval_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatoryRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requirement_reference', models.CharField(db_index=True, max_length=100)),
                ('category', models.CharField(choices=[('Environmental', 'Environmental Standards'), ('Safety & Health', 'Safety & Occupational Health'), ('Building Codes', 'National Building Codes'), ('Legal & Planning', 'Planning & Urban Regulations')], default='Environmental', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('authority', models.CharField(default='EPA', max_length=255)),
                ('status', models.CharField(choices=[('Compliant', 'Compliant'), ('At Risk', 'At Risk'), ('Non-Compliant', 'Non-Compliant')], default='Compliant', max_length=50)),
                ('last_checked', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['category', 'requirement_reference'],
            },
        ),
        migrations.CreateModel(
            name='NonConformanceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ncr_reference', models.CharField(blank=True, db_index=True, default=apps.compliance.models.generate_ncr_ref, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('Critical', 'Critical (Stop-Work Risk)'), ('Major', 'Major (High Non-Conformance)'), ('Minor', 'Minor (Standard Deviation)')], default='Major', max_length=50)),
                ('category', models.CharField(choices=[('Environmental', 'Environmental'), ('Safety', 'Safety & Health'), ('Quality', 'Quality Assurance / Materials'), ('Structural', 'Structural & Engineering'), ('General', 'General Compliance')], default='Safety', max_length=50)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed / Resolved')], default='Open', max_length=50)),
                ('reported_by_name', models.CharField(default='J. Doe (Safety)', max_length=255)),
                ('assignee_name', models.CharField(default='Lead Contractor', max_length=255)),
                ('source', models.CharField(choices=[('INSPECTION', 'Field Inspection Finding'), ('SITE_MONITORING', 'Site Monitoring / Defect'), ('BIM_CLASH', 'BIM Model Clash Interference'), ('GPR_SCAN', 'Subsurface / GPR Anomaly'), ('PERMIT_REVIEW', 'Permit Review Non-Conformance'), ('MANUAL', 'Direct Regulatory Citation')], default='MANUAL', max_length=50)),
                ('source_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('escalation_level', models.IntegerField(default=1)),
                ('last_escalated_at', models.DateTimeField(blank=True, null=True)),
                ('date_logged', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ncrs', to='projects.project')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_ncrs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_logged'],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveActionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capa_reference', models.CharField(blank=True, db_index=True, default=apps.compliance.models.generate_capa_ref, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('action_plan', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='High', max_length=50)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in-progress', 'In Progress'), ('review', 'Under Review'), ('closed', 'Closed')], default='todo', max_length=50)),
                ('assignee_name', models.CharField(default='HSE Officer', max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('comments_count', models.IntegerField(default=0)),
                ('attachments_count', models.IntegerField(default=0)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ncr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capas', to='compliance.nonconformancereport')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capas', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_reference', models.CharField(blank=True, db_index=True, default=apps.compliance.models.generate_rev_ref, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('review_type', models.CharField(choices=[('Safety', 'Safety Audit'), ('Building Code', 'Building Code Verification'), ('Environmental', 'Environmental Impact Check'), ('Quality', 'Quality Assurance Review')], default='Safety', max_length=50)),
                ('auditor_name', models.CharField(default='J. Doe (Lead)', max_length=255)),
                ('stage', models.CharField(choices=[('Initiation', 'Initiation'), ('Audit in Progress', 'Audit in Progress'), ('Reporting', 'Reporting'), ('Final Review', 'Final Review'), ('Completed', 'Completed')], default='Initiation', max_length=50)),
                ('progress', models.IntegerField(default=10)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('findings_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reviews', to='projects.project')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_reference', models.CharField(blank=True, db_index=True, default=apps.compliance.models.generate_cert_ref, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Environmental', 'Environmental Clearance'), ('Safety', 'Fire & Site Safety'), ('Quality', 'Quality Management'), ('Building Code', 'Structural Fitness Certificate')], default='Environmental', max_length=50)),
                ('authority', models.CharField(default='Environmental Protection Agency (EPA)', max_length=255)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active / Valid'), ('Expiring Soon', 'Expiring Soon (<30 Days)'), ('Expired', 'Expired'), ('Revoked', 'Revoked / Suspended')], default='Active', max_length=50)),
                ('qr_verification_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate_file_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_certificates', to='projects.project')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
    ]
