# Generated by Django 4.2.30 on 2026-08-25 02:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_applicable_regulations_project_approval_date_and_more'),
        ('compliance', '0002_alter_compliancecertificate_issue_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=255)),
                ('trigger_category', models.CharField(choices=[('BIM', 'BIM & Model Deviation'), ('Inspection', 'Site & Field Inspection'), ('Quality', 'Material & Quality Assurance'), ('Safety', 'Life Safety & Structural'), ('Worker', 'Workforce & Labor Compliance'), ('General', 'General Statutory Enforcement')], default='General', max_length=50)),
                ('action_required', models.CharField(max_length=255)),
                ('escalation_level', models.IntegerField(default=1)),
                ('sla_hours', models.IntegerField(default=48)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['escalation_level', 'rule_name'],
            },
        ),
        migrations.AddField(
            model_name='compliancereview',
            name='findings_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compliancereview',
            name='ncrs_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regulatoryrequirement',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regulatoryrequirement',
            name='evidence_required',
            field=models.CharField(blank=True, default='Test Certificate / Inspection Signoff', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='regulatoryrequirement',
            name='mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='regulatoryrequirement',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regulatory_requirements', to='projects.project'),
        ),
        migrations.AddField(
            model_name='regulatoryrequirement',
            name='verification_method',
            field=models.CharField(default='Physical Inspection & Documentation', max_length=255),
        ),
    ]
