name: Node.js CI

on:
  push:
    branches: [ "main", "reviews", "develop" ]
  pull_request:
    branches: [ "main", "reviews", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Install dependencies & Build
      run: |
        if [ -f "package.json" ]; then
          npm ci
          npm run build
          npm test
        elif [ -d "frontend" ] && [ -f "frontend/package.json" ]; then
          cd frontend
          npm ci
          npm run build
          npm test
        else
          echo "No package.json found"
          exit 1
        fi

